import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { apiRequest } from '../services/api'
import './AdminDashboard.css'

const panel = { background: '#151515', border: '1px solid #333', borderRadius: 12, padding: '1rem', marginBottom: '1rem' }
const input = { padding: '.5rem', background: '#0e0e0e', color: '#fff', border: '1px solid #444', borderRadius: 5, margin: '.25rem', minWidth: 140 }
const button = { padding: '.5rem .7rem', border: 0, borderRadius: 5, background: '#c9a84c', color: '#111', fontWeight: 700, cursor: 'pointer', margin: '.2rem' }

export default function AdminDashboard() {
  const navigate = useNavigate(); const token = sessionStorage.getItem('token')
  const [stats, setStats] = useState(null); const [users, setUsers] = useState([]); const [providers, setProviders] = useState([]); const [bookings, setBookings] = useState([]); const [complaints, setComplaints] = useState([]); const [plans, setPlans] = useState([]); const [promotions, setPromotions] = useState([]); const [tickets, setTickets] = useState([]); const [report, setReport] = useState(null); const [message, setMessage] = useState(''); const [search, setSearch] = useState(''); const [promo, setPromo] = useState({ title: '', code: '', discount_pct: '', starts_at: '', ends_at: '' }); const [plan, setPlan] = useState({ title: '', type: 'single', price_monthly: '', duration_days: 30, features: '' })
  const load = async () => { if (!token) return navigate('/login', { replace: true }); try { const [metricRows, userRows, providerRows, bookingRows, complaintRows, planRows, promotionRows, ticketRows, reportRows] = await Promise.all([apiRequest('/admin/stats', 'GET', null, token), apiRequest(`/admin/users?search=${encodeURIComponent(search)}`, 'GET', null, token), apiRequest('/admin/providers', 'GET', null, token), apiRequest('/admin/bookings', 'GET', null, token), apiRequest('/admin/complaints', 'GET', null, token), apiRequest('/admin/subscriptions', 'GET', null, token), apiRequest('/promotions', 'GET', null, token), apiRequest('/support', 'GET', null, token), apiRequest('/admin/reports', 'GET', null, token)]); setStats(metricRows); setUsers(userRows); setProviders(providerRows); setBookings(bookingRows); setComplaints(complaintRows); setPlans(planRows); setPromotions(promotionRows); setTickets(ticketRows); setReport(reportRows) } catch (error) { setMessage(error.message) } }
  useEffect(() => { load() }, [search])
  const updateUser = async (row) => { try { await apiRequest(`/admin/users/${row.id}`, 'PUT', { active: !row.active }, token); await load() } catch (error) { setMessage(error.message) } }
  const kyc = async (row, status) => { const rejection_reason = status === 'rejected' ? window.prompt('Rejection reason (3+ characters):') : undefined; if (status === 'rejected' && !rejection_reason) return; try { await apiRequest(`/admin/providers/${row.id}/kyc`, 'PUT', { status, ...(rejection_reason ? { rejection_reason } : {}) }, token); await load() } catch (error) { setMessage(error.message) } }
  const complaint = async (row) => { const status = window.prompt('Status: open, in_review, or resolved', row.status); if (!status) return; const admin_note = window.prompt('Admin note (optional):') || undefined; try { await apiRequest(`/admin/complaints/${row.id}`, 'PUT', { status, admin_note }, token); await load() } catch (error) { setMessage(error.message) } }
  const ticket = async (row) => { const status = window.prompt('Status: open, in_progress, resolved, closed', row.status); if (!status) return; const admin_response = window.prompt('Response (optional):') || undefined; try { await apiRequest(`/support/${row.id}`, 'PUT', { status, admin_response }, token); await load() } catch (error) { setMessage(error.message) } }
  const createPlan = async (event) => { event.preventDefault(); try { await apiRequest('/admin/subscriptions', 'POST', { ...plan, price_monthly: Number(plan.price_monthly), duration_days: Number(plan.duration_days), features: plan.features.split(',').map((item) => item.trim()).filter(Boolean), entitlements: [] }, token); setPlan({ title: '', type: 'single', price_monthly: '', duration_days: 30, features: '' }); await load() } catch (error) { setMessage(error.message) } }
  const togglePlan = async (row) => { try { await apiRequest(`/admin/subscriptions/${row.id}`, 'PUT', { active: !row.active }, token); await load() } catch (error) { setMessage(error.message) } }
  const createPromo = async (event) => { event.preventDefault(); try { await apiRequest('/promotions', 'POST', { ...promo, discount_pct: Number(promo.discount_pct), starts_at: promo.starts_at || undefined, ends_at: promo.ends_at || undefined }, token); setPromo({ title: '', code: '', discount_pct: '', starts_at: '', ends_at: '' }); await load() } catch (error) { setMessage(error.message) } }
  const togglePromo = async (row) => { try { await apiRequest(`/promotions/${row.id}`, 'PUT', { active: !row.active }, token); await load() } catch (error) { setMessage(error.message) } }
  const setBooking = async (row) => { const status = window.prompt('New status: pending, assigned, in_progress, completed, cancelled', row.status); if (!status) return; const provider_id = window.prompt('Provider ID to assign/reassign (leave blank to keep current)', row.providerId || ''); try { await apiRequest(`/admin/bookings/${row.id}`, 'PUT', { status, ...(provider_id ? { provider_id: Number(provider_id) } : {}) }, token); await load() } catch (error) { setMessage(error.message) } }
  const viewKyc = async (provider) => { try { const detail = await apiRequest(`/admin/providers/${provider.id}`, 'GET', null, token); const first = detail.documents?.[0]; if (!first) return setMessage('No KYC documents uploaded.'); const response = await fetch(`${import.meta.env.VITE_API_URL || 'http://localhost:5000/api'}${first.url}`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error('Could not retrieve KYC document'); window.open(URL.createObjectURL(await response.blob()), '_blank', 'noopener,noreferrer') } catch (error) { setMessage(error.message) } }
  if (!stats) return <main className="ad-wrapper"><p>{message || 'Loading administrator dashboard…'}</p></main>
  return <main className="ad-wrapper" style={{ padding: '1.5rem', color: '#eee', maxWidth: 1300, margin: 'auto' }}><header style={{ display: 'flex', justifyContent: 'space-between' }}><div><h1>Luxora Administration</h1><p>All values below are live database data.</p></div><button style={button} onClick={() => { sessionStorage.clear(); navigate('/login') }}>Sign out</button></header>{message && <p role="status" style={{ color: '#f4cf67' }}>{message}</p>}
    <section style={panel}><h2>Platform metrics</h2><div style={{ display: 'flex', flexWrap: 'wrap', gap: '1rem' }}>{Object.entries(stats).map(([key, value]) => <div key={key}><small>{key}</small><br /><strong>{typeof value === 'number' ? value.toLocaleString() : String(value)}</strong></div>)}</div></section>
    <section style={panel}><h2>User management</h2><input style={input} placeholder="Search name or email" value={search} onChange={(event) => setSearch(event.target.value)} />{users.map((row) => <p key={row.id}>#{row.id} {row.name} — {row.email} ({row.role}) <b>{row.active ? 'ACTIVE' : 'INACTIVE'}</b> <button style={button} onClick={() => updateUser(row)}>{row.active ? 'Deactivate' : 'Activate'}</button></p>)}</section>
    <section style={panel}><h2>Providers and KYC</h2>{providers.map((row) => <article key={row.id}><b>{row.name}</b> — {row.category}; KYC: {row.kyc_status} <button style={button} onClick={() => viewKyc(row)}>View secure documents</button>{row.kyc_status === 'pending' && <><button style={button} onClick={() => kyc(row, 'approved')}>Approve</button><button style={{ ...button, background: '#e06c75' }} onClick={() => kyc(row, 'rejected')}>Reject</button></>}</article>)}</section>
    <section style={panel}><h2>Subscription plans</h2><form onSubmit={createPlan}><input style={input} placeholder="Title" value={plan.title} onChange={(e) => setPlan({ ...plan, title: e.target.value })} required /><input style={input} type="number" placeholder="Price" value={plan.price_monthly} onChange={(e) => setPlan({ ...plan, price_monthly: e.target.value })} required /><input style={input} type="number" placeholder="Duration days" value={plan.duration_days} onChange={(e) => setPlan({ ...plan, duration_days: e.target.value })} required /><input style={input} placeholder="Features, comma separated" value={plan.features} onChange={(e) => setPlan({ ...plan, features: e.target.value })} /><button style={button}>Create plan</button></form>{plans.map((row) => <p key={row.id}>{row.title} — LKR {row.priceMonthly}; {row.durationDays} days; {row.active ? 'Active' : 'Disabled'} <button style={button} onClick={() => togglePlan(row)}>{row.active ? 'Disable' : 'Enable'}</button></p>)}</section>
    <section style={panel}><h2>Bookings</h2>{bookings.map((row) => <p key={row.id}>#{row.id} {row.service_title} — {row.customer_name}; {row.bookingDate} {row.bookingTime}; {row.status}; provider: {row.provider_name || 'none'} <button style={button} onClick={() => setBooking(row)}>Manage</button></p>)}</section>
    <section style={panel}><h2>Complaints</h2>{complaints.map((row) => <p key={row.id}>#{row.id} {row.customer_name}: {row.subject} — {row.status} <button style={button} onClick={() => complaint(row)}>Update</button></p>)}</section>
    <section style={panel}><h2>Promotions</h2><form onSubmit={createPromo}><input style={input} placeholder="Title" value={promo.title} onChange={(e) => setPromo({ ...promo, title: e.target.value })} required /><input style={input} placeholder="Code" value={promo.code} onChange={(e) => setPromo({ ...promo, code: e.target.value })} /><input style={input} type="number" placeholder="Discount %" value={promo.discount_pct} onChange={(e) => setPromo({ ...promo, discount_pct: e.target.value })} required /><input style={input} type="date" value={promo.starts_at} onChange={(e) => setPromo({ ...promo, starts_at: e.target.value })} /><input style={input} type="date" value={promo.ends_at} onChange={(e) => setPromo({ ...promo, ends_at: e.target.value })} /><button style={button}>Create promotion</button></form>{promotions.map((row) => <p key={row.id}>{row.title} ({row.code || 'no code'}) {row.discount_percent}% <button style={button} onClick={() => togglePromo(row)}>{row.active ? 'Disable' : 'Enable'}</button></p>)}</section>
    <section style={panel}><h2>Customer support</h2>{tickets.map((row) => <p key={row.id}>#{row.id} {row.user?.name}: {row.subject}; {row.status}; {row.adminResponse || 'No response'} <button style={button} onClick={() => ticket(row)}>Respond/update</button></p>)}</section>
    <section style={panel}><h2>Reports and analysis</h2><p>Customers: {report?.summary?.customers}; Providers: {report?.summary?.providers}; Bookings: {report?.summary?.bookings}; Completed: {report?.summary?.completedBookings}; Revenue: LKR {Number(report?.summary?.revenue || 0).toLocaleString()}; Average rating: {Number(report?.summary?.averageRating || 0).toFixed(2)}</p><h3>Popular services</h3>{report?.servicePopularity?.map((row) => <p key={row.serviceId}>{row.service}: {row.bookings} bookings</p>)}<h3>Provider performance</h3>{report?.providerPerformance?.map((row) => <p key={row.providerId}>{row.provider}: {row.completedBookings} completed, LKR {Number(row.serviceValue).toLocaleString()}</p>)}</section>
  </main>
}
