import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { API_BASE, apiRequest } from '../services/api'
import PortalShell, { EmptyState, LoadingState, Panel, Status } from '../components/PortalShell'
import { FilterPills, Modal, PromptDialog, SearchInput } from '../components/ui'
import './AdminDashboard.css'

// In-app KYC review (ported from the OG audit viewer): gallery of uploaded
// documents, inline preview of images/PDFs fetched with the session token,
// and approve/reject with the required rejection reason.
function KycModal({ provider, token, onClose, onApprove, onReject }) {
  const [detail, setDetail] = useState(null)
  const [activeDoc, setActiveDoc] = useState(null)
  const [rejecting, setRejecting] = useState(false)
  const [reason, setReason] = useState('')
  const [error, setError] = useState('')
  useEffect(() => {
    let cancelled = false
    apiRequest(`/admin/providers/${provider.id}`, 'GET', null, token)
      .then((row) => { if (!cancelled) setDetail(row) })
      .catch((err) => { if (!cancelled) setError(err.message) })
    return () => { cancelled = true }
  }, [provider.id, token])
  const openDoc = async (document) => {
    setError('')
    try {
      const response = await fetch(`${API_BASE}/uploads/kyc/${document.id}`, { headers: { Authorization: `Bearer ${token}` } })
      if (!response.ok) throw new Error('Could not retrieve document')
      setActiveDoc({ url: URL.createObjectURL(await response.blob()), mimeType: document.mimeType, name: document.originalName })
    } catch (err) { setError(err.message) }
  }
  return <Modal wide kicker={`Provider #${provider.id}`} title={`KYC review · ${provider.name}`} onClose={onClose} footer={rejecting
    ? <>
        <button className="ui-button ui-button--text" onClick={() => setRejecting(false)}>Back</button>
        <button className="ui-button ui-button--danger" disabled={reason.trim().length < 3} onClick={() => onReject(reason.trim())}>Confirm rejection</button>
      </>
    : <>
        {detail && <small style={{ marginRight: 'auto', color: 'var(--p-muted)' }}>{detail.kycDocuments?.length || 0} document(s) on file</small>}
        {String(provider.kyc_status).toLowerCase() === 'pending' && <>
          <button className="ui-button ui-button--danger" onClick={() => setRejecting(true)}>Reject</button>
          <button className="ui-button ui-button--primary" onClick={onApprove}>Approve provider</button>
        </>}
        <button className="ui-button ui-button--text" onClick={onClose}>Close</button>
      </>}>
    {rejecting ? <label className="ui-field ui-field--full" style={{ display: 'grid', gap: 6 }}>
      <span>Rejection reason (min 3 characters) *</span>
      <textarea value={reason} onChange={(event) => setReason(event.target.value)} rows={3} placeholder="Why is this application rejected?" maxLength={500} />
    </label> : <>
      {error && <p className="ui-field-error">{error}</p>}
      {!detail ? <p className="quiet-copy">Loading provider details…</p> : <>
        <div className="kyc-meta">
          <span>Email <b>{detail.user?.email || '—'}</b></span>
          <span>Phone <b>{detail.user?.phone || '—'}</b></span>
          <span>Town <b>{detail.user?.town || '—'}</b></span>
          <span>Category <b>{provider.category || '—'}</b></span>
        </div>
        <div className="kyc-gallery" style={{ marginTop: 14 }}>
          {detail.kycDocuments?.length ? detail.kycDocuments.map((document) => <button key={document.id} className={activeDoc?.name === document.originalName ? 'is-active' : ''} onClick={() => openDoc(document)}>{document.documentType} · {document.originalName}</button>) : <p className="quiet-copy">No documents uploaded.</p>}
        </div>
        <div className="kyc-preview">
          {activeDoc ? (activeDoc.mimeType === 'application/pdf'
            ? <iframe title={activeDoc.name} src={activeDoc.url} />
            : <img alt={activeDoc.name} src={activeDoc.url} />)
            : <p className="quiet-copy" style={{ padding: 40 }}>Select a document to preview it securely.</p>}
        </div>
      </>}
    </>}
  </Modal>
}

export default function AdminDashboard() {
  const navigate = useNavigate(); const token = sessionStorage.getItem('token')
  const [stats, setStats] = useState(null); const [users, setUsers] = useState([]); const [providers, setProviders] = useState([]); const [bookings, setBookings] = useState([]); const [complaints, setComplaints] = useState([]); const [plans, setPlans] = useState([]); const [categories, setCategories] = useState([]); const [promotions, setPromotions] = useState([]); const [tickets, setTickets] = useState([]); const [refunds, setRefunds] = useState([]); const [report, setReport] = useState(null); const [scheduling, setScheduling] = useState(null); const [message, setMessage] = useState(''); const [search, setSearch] = useState(''); const [promo, setPromo] = useState({ title: '', code: '', discount_pct: '', starts_at: '', ends_at: '' }); const [plan, setPlan] = useState({ title: '', type: 'single', price_monthly: '', duration_days: 30, features: '', category_id: '', units: '' })
  const [dialog, setDialog] = useState(null); const [bookingSearch, setBookingSearch] = useState(''); const [bookingDate, setBookingDate] = useState('')
  const load = async () => { if (!token) return navigate('/login', { replace: true }); try { const [metricRows, reportRows, categoryRows] = await Promise.all([apiRequest('/admin/stats', 'GET', null, token), apiRequest('/admin/reports', 'GET', null, token), apiRequest('/categories', 'GET', null, token)]); setStats(metricRows); setReport(reportRows); setCategories(categoryRows); const [userRows, providerRows, bookingRows, complaintRows] = await Promise.all([apiRequest(`/admin/users?search=${encodeURIComponent(search)}`, 'GET', null, token), apiRequest('/admin/providers', 'GET', null, token), apiRequest('/admin/bookings', 'GET', null, token), apiRequest('/admin/complaints', 'GET', null, token)]); setUsers(userRows); setProviders(providerRows); setBookings(bookingRows); setComplaints(complaintRows); const [planRows, promotionRows, ticketRows, refundRows] = await Promise.all([apiRequest('/admin/subscriptions', 'GET', null, token), apiRequest('/promotions/all', 'GET', null, token), apiRequest('/support', 'GET', null, token), apiRequest('/admin/refunds', 'GET', null, token)]); setPlans(planRows); setPromotions(promotionRows); setTickets(ticketRows); setRefunds(refundRows); setScheduling(await apiRequest('/admin/settings/scheduling', 'GET', null, token).catch(() => null)) } catch (error) { setMessage(error.message) } }
  useEffect(() => { load() }, [search])
  const updateUser = async (row) => { try { await apiRequest(`/admin/users/${row.id}`, 'PUT', { active: !row.active }, token); await load() } catch (error) { setMessage(error.message) } }
  const approveKyc = async (provider) => { try { await apiRequest(`/admin/providers/${provider.id}/kyc`, 'PUT', { status: 'approved' }, token); setDialog(null); await load() } catch (error) { setMessage(error.message); setDialog(null) } }
  const rejectKyc = async (provider, rejection_reason) => { try { await apiRequest(`/admin/providers/${provider.id}/kyc`, 'PUT', { status: 'rejected', rejection_reason }, token); setDialog(null); await load() } catch (error) { setMessage(error.message); setDialog(null) } }
  const complaint = async (values) => { const row = dialog.row; try { await apiRequest(`/admin/complaints/${row.id}`, 'PUT', { status: values.status, admin_note: values.admin_note || undefined }, token); setDialog(null); await load() } catch (error) { setMessage(error.message); setDialog(null) } }
  const refund = async (values) => { const { row, decision } = dialog; try { const result = await apiRequest(`/admin/refunds/${row.id}`, 'PUT', { status: decision, admin_note: values.admin_note || '' }, token); setMessage(`Refund ${result.status}.`); setDialog(null); await load() } catch (error) { setMessage(error.message); setDialog(null) } }
  const ticket = async (values) => { const row = dialog.row; try { await apiRequest(`/support/${row.id}`, 'PUT', { status: values.status, admin_response: values.admin_response || undefined }, token); setDialog(null); await load() } catch (error) { setMessage(error.message); setDialog(null) } }
  const createPlan = async (event) => { event.preventDefault(); try { await apiRequest('/admin/subscriptions', 'POST', { ...plan, price_monthly: Number(plan.price_monthly), duration_days: Number(plan.duration_days), features: plan.features.split(',').map((item) => item.trim()).filter(Boolean), entitlements: [{ category_id: Number(plan.category_id), units: Number(plan.units) }] }, token); setPlan({ title: '', type: 'single', price_monthly: '', duration_days: 30, features: '', category_id: '', units: '' }); await load() } catch (error) { setMessage(error.message) } }
  const togglePlan = async (row) => { try { await apiRequest(`/admin/subscriptions/${row.id}`, 'PUT', { active: !row.active }, token); await load() } catch (error) { setMessage(error.message) } }
  const createPromo = async (event) => { event.preventDefault(); try { await apiRequest('/promotions', 'POST', { ...promo, discount_pct: Number(promo.discount_pct), starts_at: promo.starts_at || undefined, ends_at: promo.ends_at || undefined }, token); setPromo({ title: '', code: '', discount_pct: '', starts_at: '', ends_at: '' }); await load() } catch (error) { setMessage(error.message) } }
  const togglePromo = async (row) => { try { await apiRequest(`/promotions/${row.id}`, 'PUT', { active: !row.active }, token); await load() } catch (error) { setMessage(error.message) } }
  const setBooking = async (values) => { const row = dialog.row; try { await apiRequest(`/admin/bookings/${row.id}`, 'PUT', { status: values.status, ...(values.provider_id ? { provider_id: Number(values.provider_id) } : {}) }, token); setDialog(null); await load() } catch (error) { setMessage(error.message); setDialog(null) } }
  const saveScheduling = async (values) => { try { await apiRequest('/admin/settings/scheduling', 'PUT', { auto_assignment_cooldown_hours: Number(values.cooldown), auto_assignment_start_hour: Number(values.start), auto_assignment_end_hour: Number(values.end) }, token); setDialog(null); await load() } catch (error) { setMessage(error.message); setDialog(null) } }
  if (!stats) return <LoadingState title={message || 'Preparing Luxora operations'} />
  const metricLabels = { totalUsers: 'Members', totalProviders: 'Providers', pendingProviders: 'KYC pending', activeSubscriptions: 'Active subscriptions', totalBookings: 'Bookings', completedBookings: 'Completed', totalRevenue: 'Revenue', openComplaints: 'Open complaints' }
  const filteredBookings = bookings.filter((row) => (!bookingDate || row.bookingDate === bookingDate) && (!bookingSearch.trim() || [row.service_title, row.customer_name, row.provider_name, `#${row.id}`].filter(Boolean).join(' ').toLowerCase().includes(bookingSearch.trim().toLowerCase())))
  const attention = [
    ...bookings.filter((row) => String(row.status).toLowerCase() === 'pending').map((row) => ({ id: `booking-${row.id}`, type: 'Booking awaiting assignment', label: `${row.service_title} · ${row.customer_name}`, tone: 'pending' })),
    ...providers.filter((row) => String(row.kyc_status).toLowerCase() === 'pending').map((row) => ({ id: `provider-${row.id}`, type: 'KYC verification', label: row.name, tone: 'pending' })),
    ...refunds.filter((row) => row.status === 'REQUESTED').map((row) => ({ id: `refund-${row.id}`, type: 'Refund review', label: `${row.user.name} · ${row.subscription.plan.title}`, tone: 'pending' })),
    ...complaints.filter((row) => !['resolved', 'closed'].includes(String(row.status).toLowerCase())).map((row) => ({ id: `complaint-${row.id}`, type: 'Member care', label: `${row.customer_name} · ${row.subject}`, tone: 'pending' })),
  ]
  return <PortalShell role="Admin" userName="Operations team" title="Dashboard" heroTitle="Platform overview" subtitle="A clear view of service health, member care and the decisions that keep the platform moving." notice={message} onSignOut={() => { sessionStorage.clear(); navigate('/login') }} navItems={[{ id: 'overview', label: 'Overview' }, { id: 'bookings', label: 'Bookings' }, { id: 'members', label: 'Customers' }, { id: 'providers', label: 'Providers' }, { id: 'packages', label: 'Packages' }, { id: 'care', label: 'Care desk' }, { id: 'operations', label: 'Operations' }]}>
    <Panel id="overview" className="admin-overview"><div className="section-heading"><div><p className="portal-kicker">Today's overview</p><h2>Platform operating picture</h2></div><Status tone="active">Live data</Status></div><div className="admin-metrics">{Object.entries(stats).map(([key, value]) => <article key={key}><span>{metricLabels[key] || key.replace(/([A-Z])/g, ' $1')}</span><strong>{key.toLowerCase().includes('revenue') ? `LKR ${Number(value).toLocaleString()}` : typeof value === 'number' ? value.toLocaleString() : String(value)}</strong></article>)}</div></Panel>
    <section className="attention-strip"><div><p className="portal-kicker">Attention required</p><h2>{attention.length ? `${attention.length} item${attention.length === 1 ? '' : 's'} need a decision` : 'Everything is under control'}</h2></div><div className="attention-items">{attention.length ? attention.slice(0, 4).map((item) => <article key={item.id}><Status tone={item.tone}>{item.type}</Status><b>{item.label}</b></article>) : <p>No pending bookings, KYC reviews, refunds, or member-care requests.</p>}</div></section>
    <div className="admin-operations-grid"><Panel id="bookings" className="admin-bookings"><div className="section-heading"><div><p className="portal-kicker">Today's services</p><h2>Bookings in motion</h2></div><SearchInput value={bookingSearch} onChange={setBookingSearch} placeholder="Search service or customer" ariaLabel="Search bookings" /></div><div style={{ display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap', margin: '12px 0' }}><label className="date-picker"><span>Filter date</span><input type="date" value={bookingDate} onChange={(event) => setBookingDate(event.target.value)} /></label>{bookingDate && <button className="ui-button ui-button--text" onClick={() => setBookingDate('')}>Clear date ✕</button>}</div>{filteredBookings.length ? <div className="admin-table">{filteredBookings.map((row) => <article key={row.id}><time>{row.bookingDate}<b>{row.bookingTime}</b></time><div><strong>{row.service_title}</strong><small>{row.customer_name} · {row.provider_name || 'Unassigned provider'}</small></div><Status tone={String(row.status).toLowerCase()}>{row.status}</Status><button className="ui-button ui-button--secondary" onClick={() => setDialog({ type: 'booking', row })}>Manage</button></article>)}</div> : <EmptyState title="No bookings match">Adjust the search or date filter to see platform bookings.</EmptyState>}</Panel><Panel className="admin-insight"><p className="portal-kicker">Business performance</p><h2>Service demand</h2><div className="performance-list">{report?.servicePopularity?.length ? report.servicePopularity.map((row) => <div key={row.serviceId}><span>{row.service}</span><b>{row.bookings}</b><i style={{ width: `${Math.min(100, row.bookings * 15)}%` }} /></div>) : <EmptyState title="No trend data yet">Performance appears as real bookings are completed.</EmptyState>}</div><h3>Provider performance</h3>{report?.providerPerformance?.slice(0, 4).map((row) => <p className="provider-performance" key={row.providerId}><span>{row.provider}</span><b>{row.completedBookings} completed</b></p>)}</Panel></div>
    <Panel id="members" className="admin-members"><div className="section-heading"><div><p className="portal-kicker">Customer care</p><h2>Member management</h2></div><input className="admin-search" placeholder="Search name or email" value={search} onChange={(event) => setSearch(event.target.value)} aria-label="Search members" /></div>{users.length ? <div className="admin-table">{users.map((row) => <article key={row.id}><div className="table-avatar">{row.name?.slice(0, 1)}</div><div><strong>{row.name}</strong><small>{row.email} · {row.role}</small></div><Status tone={row.active ? 'active' : 'cancelled'}>{row.active ? 'Active' : 'Inactive'}</Status><button className="ui-button ui-button--secondary" onClick={() => updateUser(row)}>{row.active ? 'Deactivate' : 'Activate'}</button></article>)}</div> : <EmptyState title="No members found">Adjust your search to find another member.</EmptyState>}</Panel>
    <Panel id="providers" className="admin-providers"><p className="portal-kicker">Provider quality</p><h2>Providers & verification</h2>{providers.length ? <div className="provider-admin-grid">{providers.map((row) => <article key={row.id}><div><div className="table-avatar">{row.name?.slice(0, 1)}</div><Status tone={String(row.kyc_status).toLowerCase()}>{row.kyc_status}</Status></div><h3>{row.name}</h3><p>{row.category || 'Luxora provider'}</p><div className="provider-admin-actions"><button className="ui-button ui-button--secondary" onClick={() => setDialog({ type: 'kyc', row })}>Review KYC</button>{row.kyc_status === 'pending' && <><button className="ui-button ui-button--primary" onClick={() => approveKyc(row)}>Approve</button><button className="ui-button ui-button--text danger" onClick={() => setDialog({ type: 'kyc', row })}>Reject</button></>}</div></article>)}</div> : <EmptyState title="No providers listed">Registered providers will appear here for review.</EmptyState>}</Panel>
    <Panel id="packages" className="admin-packages"><p className="portal-kicker">Package catalogue</p><h2>Memberships & entitlements</h2>{scheduling && <form className="luxora-form admin-form-grid" onSubmit={createPlan}><input placeholder="Package name" value={plan.title} onChange={(e) => setPlan({ ...plan, title: e.target.value })} required /><select value={plan.type} onChange={(e) => setPlan({ ...plan, type: e.target.value })}><option value="single">Individual package</option><option value="combo">Combo package</option></select><input type="number" placeholder="Price" value={plan.price_monthly} onChange={(e) => setPlan({ ...plan, price_monthly: e.target.value })} required /><select value={plan.category_id} onChange={(e) => setPlan({ ...plan, category_id: e.target.value })} required><option value="">Covered service</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><input type="number" min="1" placeholder="Included visits" value={plan.units} onChange={(e) => setPlan({ ...plan, units: e.target.value })} required /><button className="ui-button ui-button--primary">Create package</button></form>}<div className="package-admin-list">{plans.map((row) => <article key={row.id}><div><Status tone={row.active ? 'active' : 'cancelled'}>{row.type}</Status><h3>{row.title}</h3><p>{row.entitlements?.map((item) => `${item.category?.name || 'Service'}: ${item.units}`).join(' · ') || 'No entitlement configured'}</p></div><b>LKR {Number(row.priceMonthly).toLocaleString()}</b>{scheduling && <button className="ui-button ui-button--secondary" onClick={() => togglePlan(row)}>{row.active ? 'Disable' : 'Enable'}</button>}</article>)}</div></Panel>
    <div id="care" className="admin-care-grid"><Panel><p className="portal-kicker">Member care</p><h2>Complaints</h2>{complaints.length ? complaints.map((row) => <article className="care-row" key={row.id}><Status tone={String(row.status).toLowerCase()}>{row.status}</Status><div><b>{row.subject}</b><p>{row.customer_name}</p></div><button className="ui-button ui-button--secondary" onClick={() => setDialog({ type: 'complaint', row })}>Update</button></article>) : <EmptyState title="No open complaints">Member feedback requiring care will appear here.</EmptyState>}</Panel><Panel><p className="portal-kicker">Support inbox</p><h2>Customer support</h2>{tickets.length ? tickets.map((row) => <article className="care-row" key={row.id}><Status tone={String(row.status).toLowerCase()}>{row.status}</Status><div><b>{row.subject}</b><p>{row.user?.name || 'Customer'} · {row.adminResponse || 'Awaiting response'}</p></div><button className="ui-button ui-button--secondary" onClick={() => setDialog({ type: 'ticket', row })}>Respond</button></article>) : <EmptyState title="Inbox clear">New member support requests will appear here.</EmptyState>}</Panel></div>
    <Panel className="admin-refunds"><p className="portal-kicker">Financial operations</p><h2>Refund requests</h2>{refunds.length ? <div className="admin-table">{refunds.map((row) => <article key={row.id}><div><strong>{row.user.name}</strong><small>{row.subscription.plan.title} · {row.payment?.expectedCurrency} {row.payment?.expectedAmount}</small></div><Status tone={String(row.status).toLowerCase()}>{row.status}</Status><div className="refund-actions">{row.status === 'REQUESTED' && <><button className="ui-button ui-button--primary" onClick={() => setDialog({ type: 'refund', row, decision: 'APPROVED' })}>Approve</button><button className="ui-button ui-button--text danger" onClick={() => setDialog({ type: 'refund', row, decision: 'REJECTED' })}>Reject</button></>}{row.adminNote && <small>{row.adminNote}</small>}</div></article>)}</div> : <EmptyState title="No refund requests">There are no refund requests requiring review.</EmptyState>}</Panel>
    <Panel id="operations" className="admin-operations"><p className="portal-kicker">Operations</p><h2>Scheduling & promotions</h2>{scheduling && <div className="scheduling-card"><div><Status tone="active">Super admin</Status><h3>Automatic assignment</h3><p>{scheduling.autoAssignmentStartHour}:00–{scheduling.autoAssignmentEndHour}:59 · {scheduling.autoAssignmentCooldownHours} hour cooldown</p></div><button className="ui-button ui-button--secondary" onClick={() => setDialog({ type: 'scheduling' })}>Change scheduling</button><button className="ui-button ui-button--text" onClick={async () => { try { await apiRequest('/admin/settings/scheduling/restore-defaults', 'POST', {}, token); await load() } catch (error) { setMessage(error.message) } }}>Restore defaults</button></div>}<form className="luxora-form admin-promo-form" onSubmit={createPromo}><input placeholder="Promotion title" value={promo.title} onChange={(e) => setPromo({ ...promo, title: e.target.value })} required /><input placeholder="Code" value={promo.code} onChange={(e) => setPromo({ ...promo, code: e.target.value })} /><input type="number" placeholder="Discount %" value={promo.discount_pct} onChange={(e) => setPromo({ ...promo, discount_pct: e.target.value })} required /><input type="date" value={promo.starts_at} onChange={(e) => setPromo({ ...promo, starts_at: e.target.value })} /><input type="date" value={promo.ends_at} onChange={(e) => setPromo({ ...promo, ends_at: e.target.value })} /><button className="ui-button ui-button--primary">Create promotion</button></form><div className="promotion-list">{promotions.map((row) => <article key={row.id}><div><b>{row.title}</b><small>{row.code || 'No code'} · {row.discount_percent}%</small></div><Status tone={row.active ? 'active' : 'cancelled'}>{row.active ? 'Active' : 'Disabled'}</Status><button className="ui-button ui-button--secondary" onClick={() => togglePromo(row)}>{row.active ? 'Disable' : 'Enable'}</button></article>)}</div></Panel>

    {dialog?.type === 'kyc' && <KycModal provider={dialog.row} token={token} onClose={() => setDialog(null)} onApprove={() => approveKyc(dialog.row)} onReject={(reason) => rejectKyc(dialog.row, reason)} />}
    {dialog?.type === 'booking' && <PromptDialog kicker={`Booking #${dialog.row.id}`} title="Manage booking" submitLabel="Save booking" fields={[{ name: 'status', label: 'Status', type: 'select', required: true, initial: String(dialog.row.status).toLowerCase(), options: [{ value: 'pending', label: 'Pending' }, { value: 'assigned', label: 'Assigned' }, { value: 'cancelled', label: 'Cancelled' }] }, { name: 'provider_id', label: 'Provider ID', type: 'number', initial: dialog.row.providerId || '', placeholder: 'Leave blank to keep current', hint: 'Service start/completion stay provider-only (photo + PIN).' }]} onSubmit={setBooking} onClose={() => setDialog(null)} />}
    {dialog?.type === 'complaint' && <PromptDialog kicker={`Complaint #${dialog.row.id}`} title="Update complaint" submitLabel="Save update" fields={[{ name: 'status', label: 'Status', type: 'select', required: true, initial: String(dialog.row.status).toLowerCase(), options: [{ value: 'open', label: 'Open' }, { value: 'in_review', label: 'In review' }, { value: 'resolved', label: 'Resolved' }] }, { name: 'admin_note', label: 'Admin note (optional)', type: 'textarea', initial: '', maxLength: 2000, full: true }]} onSubmit={complaint} onClose={() => setDialog(null)} />}
    {dialog?.type === 'ticket' && <PromptDialog kicker={`Ticket #${dialog.row.id}`} title="Respond to ticket" submitLabel="Send response" fields={[{ name: 'status', label: 'Status', type: 'select', required: true, initial: String(dialog.row.status).toLowerCase(), options: [{ value: 'open', label: 'Open' }, { value: 'in_progress', label: 'In progress' }, { value: 'resolved', label: 'Resolved' }, { value: 'closed', label: 'Closed' }] }, { name: 'admin_response', label: 'Response (optional)', type: 'textarea', initial: '', maxLength: 2000, full: true }]} onSubmit={ticket} onClose={() => setDialog(null)} />}
    {dialog?.type === 'refund' && <PromptDialog kicker={`${dialog.row.subscription.plan.title} · ${dialog.row.user.name}`} title={dialog.decision === 'APPROVED' ? 'Approve refund' : 'Reject refund'} submitLabel={dialog.decision === 'APPROVED' ? 'Approve refund' : 'Reject refund'} fields={[{ name: 'admin_note', label: 'Note (optional)', type: 'textarea', initial: '', maxLength: 2000, full: true, hint: dialog.decision === 'APPROVED' ? 'Demo refunds complete instantly; PayHere refunds settle on gateway confirmation.' : 'Share why this request is rejected.' }]} onSubmit={refund} onClose={() => setDialog(null)} />}
    {dialog?.type === 'scheduling' && <PromptDialog kicker="Super admin" title="Automatic assignment window" submitLabel="Save scheduling" fields={[{ name: 'start', label: 'Start hour (0-23)', type: 'number', required: true, min: 0, max: 23, initial: String(scheduling.autoAssignmentStartHour) }, { name: 'end', label: 'End hour (0-23)', type: 'number', required: true, min: 0, max: 23, initial: String(scheduling.autoAssignmentEndHour) }, { name: 'cooldown', label: 'Cooldown hours (1-24)', type: 'number', required: true, min: 1, max: 24, initial: String(scheduling.autoAssignmentCooldownHours), full: true }]} onSubmit={saveScheduling} onClose={() => setDialog(null)} />}
  </PortalShell>
}
