import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { apiRequest } from '../services/api'
import './CustomerDashboard.css'

const sectionStyle = { background: '#151515', border: '1px solid #333', borderRadius: 12, padding: '1rem', marginBottom: '1rem' }
const inputStyle = { width: '100%', boxSizing: 'border-box', padding: '.55rem', margin: '.3rem 0 .7rem', background: '#0e0e0e', color: '#fff', border: '1px solid #444', borderRadius: 6 }
const buttonStyle = { padding: '.55rem .8rem', border: 0, borderRadius: 6, background: '#c9a84c', color: '#111', fontWeight: 700, cursor: 'pointer', marginRight: '.4rem' }

export default function CustomerDashboard() {
  const navigate = useNavigate()
  const token = sessionStorage.getItem('token')
  const [data, setData] = useState(null)
  const [services, setServices] = useState([])
  const [plans, setPlans] = useState([])
  const [entitlements, setEntitlements] = useState([])
  const [payments, setPayments] = useState([])
  const [paymentMode, setPaymentMode] = useState({ mode: 'payhere', label: 'PayHere Sandbox' })
  const [demoPayment, setDemoPayment] = useState(null)
  const [notes, setNotes] = useState([])
  const [tickets, setTickets] = useState([])
  const [profile, setProfile] = useState({ name: '', email: '', town: '', phone: '' })
  const [otp, setOtp] = useState('')
  const [booking, setBooking] = useState({ service_id: '', booking_date: '', booking_time: '' })
  const [ticket, setTicket] = useState({ subject: '', message: '', priority: 'NORMAL' })
  const [complaint, setComplaint] = useState({ subject: '', description: '' })
  const [submittedComplaints, setSubmittedComplaints] = useState([])
  const [message, setMessage] = useState('')
  const [busy, setBusy] = useState(false)

  const load = async () => {
    if (!token) return navigate('/login', { replace: true })
    try {
      const [dashboard, catalogue, planRows, entitlementRows, paymentRows, paymentModeRow, notificationRows, ticketRows, complaintRows] = await Promise.all([
        apiRequest('/customer/dashboard', 'GET', null, token), apiRequest('/services'), apiRequest('/subscriptions'), apiRequest('/subscriptions/entitlements', 'GET', null, token), apiRequest('/payments/my', 'GET', null, token), apiRequest('/payments/mode', 'GET', null, token), apiRequest('/notifications', 'GET', null, token), apiRequest('/support/my', 'GET', null, token), apiRequest('/complaints/my', 'GET', null, token),
      ])
      setData(dashboard); setProfile({ name: dashboard.profile.name || '', email: dashboard.profile.email || '', town: dashboard.profile.town || '', phone: dashboard.profile.phone || '' })
      setServices(catalogue); setPlans(planRows); setEntitlements(entitlementRows.entitlements || entitlementRows); setPayments(paymentRows.payments || []); setPaymentMode(paymentModeRow); setNotes(notificationRows); setTickets(ticketRows); setSubmittedComplaints(complaintRows)
    } catch (error) { setMessage(error.message) }
  }
  useEffect(() => { load() }, [])
  const availableServiceIds = useMemo(() => new Set(entitlements.filter((item) => item.remaining_units > 0).map((item) => item.category_id)), [entitlements])
  const submitProfile = async (event) => { event.preventDefault(); setBusy(true); try { await apiRequest('/profile', 'PUT', profile, token); setMessage('Profile saved.'); await load() } catch (error) { setMessage(error.message) } finally { setBusy(false) } }
  const sendOtp = async () => { try { await apiRequest('/profile/phone/send', 'POST', { phone: profile.phone }, token); setMessage('Verification code sent to your phone.') } catch (error) { setMessage(error.message) } }
  const verifyOtp = async () => { try { await apiRequest('/profile/phone/verify', 'POST', { phone: profile.phone, code: otp }, token); setMessage('Phone verified.'); await load() } catch (error) { setMessage(error.message) } }
  const createBooking = async (event) => { event.preventDefault(); setBusy(true); try { const result = await apiRequest('/bookings', 'POST', { ...booking, service_id: Number(booking.service_id) }, token); setMessage(`Booking #${result.booking_id} created (${result.status}). Start PIN: ${result.start_pin}; completion PIN: ${result.completion_pin}`); setBooking({ service_id: '', booking_date: '', booking_time: '' }); await load() } catch (error) { setMessage(error.message) } finally { setBusy(false) } }
  const cancelBooking = async (id) => { const reason = window.prompt('Cancellation reason (at least 3 characters):'); if (!reason) return; try { await apiRequest(`/bookings/${id}/cancel`, 'PUT', { confirmed: true, reason }, token); await load() } catch (error) { setMessage(error.message) } }
  const showPins = async (id) => { try { const pins = await apiRequest(`/bookings/${id}/pins`, 'GET', null, token); setMessage(`Booking #${id} — Start PIN: ${pins.start_pin}; Completion PIN: ${pins.completion_pin}`) } catch (error) { setMessage(error.message) } }
  const cancelMembership = async (id) => { if (!window.confirm('Cancel this membership?')) return; try { await apiRequest(`/subscriptions/${id}/cancel`, 'PUT', { confirmed: true }, token); await load() } catch (error) { setMessage(error.message) } }
  const setAutoRenew = async (id, auto_renew) => { try { await apiRequest(`/subscriptions/${id}/auto-renew`, 'PUT', { auto_renew }, token); await load() } catch (error) { setMessage(error.message) } }
  const reschedule = async (row) => { const booking_date = window.prompt('New date (YYYY-MM-DD)', row.bookingDate); const booking_time = window.prompt('New time', row.bookingTime); const reason = window.prompt('Reason'); if (!booking_date || !booking_time || !reason) return; try { await apiRequest(`/bookings/${row.id}/reschedule`, 'PUT', { booking_date, booking_time, reason, confirmed: true }, token); await load() } catch (error) { setMessage(error.message) } }
  const startPayment = async (plan) => { setBusy(true); try { if (paymentMode.mode === 'demo') { setDemoPayment(await apiRequest('/payments/demo/order', 'POST', { plan_id: plan.id, auto_renew: false }, token)); setBusy(false); return } const order = await apiRequest('/payments/payhere/order', 'POST', { plan_id: plan.id }, token); const form = document.createElement('form'); form.method = 'POST'; form.action = order.checkoutUrl; Object.entries(order.fields).forEach(([name, value]) => { const input = document.createElement('input'); input.type = 'hidden'; input.name = name; input.value = value || ''; form.appendChild(input) }); document.body.appendChild(form); form.submit() } catch (error) { setMessage(error.message); setBusy(false) } }
  const completeDemoPayment = async (outcome) => { if (!demoPayment) return; setBusy(true); try { const result = await apiRequest(`/payments/demo/${demoPayment.payment_id}/complete`, 'POST', { outcome }, token); setMessage(result.message); setDemoPayment(null); await load() } catch (error) { setMessage(error.message) } finally { setBusy(false) } }
  const sendTicket = async (event) => { event.preventDefault(); try { await apiRequest('/support', 'POST', ticket, token); setTicket({ subject: '', message: '', priority: 'NORMAL' }); setMessage('Support ticket created.'); await load() } catch (error) { setMessage(error.message) } }
  const submitComplaint = async (event) => { event.preventDefault(); setBusy(true); try { const result = await apiRequest('/complaints', 'POST', complaint, token); setComplaint({ subject: '', description: '' }); setMessage(result.message); await load(); } catch (error) { setMessage(error.message) } finally { setBusy(false) } }
  const markRead = async (id) => { try { await apiRequest(`/notifications/${id}/read`, 'PUT', {}, token); await load() } catch (error) { setMessage(error.message) } }
  if (!data) return <main className="cd-wrapper"><p>{message || 'Loading customer dashboard…'}</p></main>
  const rows = [...data.upcomingBookings, ...data.pastBookings]
  return <main className="cd-wrapper luxora-shell" style={{ color: '#eee' }}>
    <header className="portal-hero"><div><p className="luxora-eyebrow">Private member portal</p><h1 className="luxora-heading">Welcome back, {profile.name?.split(' ')[0] || 'member'}.</h1><p>Membership, concierge bookings and support—kept in one calm place.</p></div><button className="portal-signout" onClick={() => { sessionStorage.clear(); navigate('/login') }}>Sign out</button></header>
    {message && <p role="status" style={{ color: '#f4cf67' }}>{message}</p>}
    <section style={sectionStyle}><h2>Profile</h2><form onSubmit={submitProfile}><label>Name<input style={inputStyle} value={profile.name} onChange={(e) => setProfile({ ...profile, name: e.target.value })} required /></label><label>Email<input style={inputStyle} type="email" value={profile.email} onChange={(e) => setProfile({ ...profile, email: e.target.value })} required /></label><label>Service town<input style={inputStyle} value={profile.town} onChange={(e) => setProfile({ ...profile, town: e.target.value })} /></label><button style={buttonStyle} disabled={busy}>Save profile</button></form><label>Phone (E.164)<input style={inputStyle} value={profile.phone} onChange={(e) => setProfile({ ...profile, phone: e.target.value })} placeholder="+94771234567" /></label><button style={buttonStyle} onClick={sendOtp}>Send verification code</button><input style={{ ...inputStyle, maxWidth: 160 }} value={otp} onChange={(e) => setOtp(e.target.value)} placeholder="OTP" /><button style={buttonStyle} onClick={verifyOtp}>Verify phone</button></section>
    <section style={sectionStyle}><p className="luxora-eyebrow">Membership & credits</p><h2>Membership at a glance</h2>{data.activeSubscriptions.length ? data.activeSubscriptions.map((subscription) => <article className="membership-row" key={subscription.id}><div><span className="luxora-badge" data-status={subscription.status}>{subscription.status}</span><strong>{subscription.plan.title}</strong><small>{new Date(subscription.startDate).toLocaleDateString()} — {new Date(subscription.endDate).toLocaleDateString()}</small></div><div><button style={buttonStyle} onClick={() => setAutoRenew(subscription.id, !subscription.autoRenew)}>{subscription.autoRenew ? 'Disable auto-renew' : 'Enable auto-renew'}</button><button style={{ ...buttonStyle, background: '#e06c75' }} onClick={() => cancelMembership(subscription.id)}>Cancel</button></div></article>) : <p className="empty-copy">No active membership yet. Choose a plan below to unlock services.</p>}<ul className="credit-list">{entitlements.map((item) => <li key={item.category_id}><span>{item.category_name}</span><b>{item.remaining_units} remaining</b><small>of {item.entitled_units} included visits</small></li>)}</ul></section>
    <section style={sectionStyle}><h2>{paymentMode.mode === 'demo' ? 'Demo / test memberships' : 'PayHere memberships'}</h2><p>{paymentMode.label}</p>{plans.map((plan) => <article key={plan.id} style={{ marginBottom: '.8rem' }}><strong>{plan.title}</strong> — LKR {Number(plan.priceMonthly).toLocaleString()} <button style={buttonStyle} disabled={busy || plan.active === false} onClick={() => startPayment(plan)}>{paymentMode.mode === 'demo' ? 'Open demo checkout' : 'Pay securely'}</button></article>)}{demoPayment && <div style={{ border: '1px solid #c9a84c', padding: '.75rem' }}><b>DEMO / TEST CHECKOUT</b><p>{demoPayment.plan.title} — {demoPayment.plan.currency} {demoPayment.plan.amount}. No money will be charged.</p><button style={buttonStyle} disabled={busy} onClick={() => completeDemoPayment('success')}>Simulate success</button><button style={buttonStyle} disabled={busy} onClick={() => completeDemoPayment('failure')}>Simulate failure</button><button style={buttonStyle} disabled={busy} onClick={() => completeDemoPayment('cancel')}>Cancel demo payment</button></div>}<h3>Payment status</h3>{payments.map((payment) => <p key={payment.id}>#{payment.id} {payment.plan?.title}: <strong>{payment.status}</strong> ({payment.gateway}; {payment.expectedCurrency} {payment.expectedAmount})</p>)}</section>
    <section style={sectionStyle}><h2>Book a service</h2><form onSubmit={createBooking}><label>Service<select style={inputStyle} value={booking.service_id} onChange={(e) => setBooking({ ...booking, service_id: e.target.value })} required><option value="">Select an entitled service</option>{services.filter((service) => availableServiceIds.has(service.category_id)).map((service) => <option key={service.id} value={service.id}>{service.title} — {service.category_name}</option>)}</select></label><label>Date<input style={inputStyle} type="date" value={booking.booking_date} onChange={(e) => setBooking({ ...booking, booking_date: e.target.value })} required /></label><label>Time<input style={inputStyle} type="time" value={booking.booking_time} onChange={(e) => setBooking({ ...booking, booking_time: e.target.value })} required /></label><button style={buttonStyle} disabled={busy}>Create booking</button></form></section>
    <section style={sectionStyle}><h2>Your bookings</h2>{rows.map((row) => <article key={row.id} style={{ borderTop: '1px solid #333', padding: '.6rem 0' }}><strong>#{row.id} {row.service?.title}</strong> — {row.bookingDate} {row.bookingTime}; <b>{row.status}</b>; provider: {row.provider?.user?.name || row.provider_name || 'Awaiting assignment'} {row.provider?.category && `(${row.provider.category})`} {!['CANCELLED', 'COMPLETED'].includes(row.status) && <button style={buttonStyle} onClick={() => showPins(row.id)}>View PINs</button>} {['PENDING', 'ASSIGNED'].includes(row.status) && <><button style={buttonStyle} onClick={() => reschedule(row)}>Reschedule</button><button style={{ ...buttonStyle, background: '#e06c75' }} onClick={() => cancelBooking(row.id)}>Cancel</button></>}</article>)}</section>
    <section style={sectionStyle}><h2>My Complaints</h2><form onSubmit={submitComplaint}><input style={inputStyle} placeholder="Subject" value={complaint.subject} onChange={(e) => setComplaint({ ...complaint, subject: e.target.value })} required maxLength={150} /><textarea style={inputStyle} placeholder="Describe the issue" value={complaint.description} onChange={(e) => setComplaint({ ...complaint, description: e.target.value })} required maxLength={2000} /><button style={buttonStyle} disabled={busy}>Submit complaint</button></form>{submittedComplaints.map((item) => <article key={item.id}><b>#{item.id} {item.status}</b> — {item.subject}<br />{item.description}<br /><small>{new Date(item.created_at).toLocaleString()}{item.booking ? ` · Booking #${item.booking.id}` : ''}</small>{item.admin_note && <p>Admin response: {item.admin_note}</p>}</article>)}</section>
    <section style={sectionStyle}><h2>Notifications</h2>{notes.map((note) => <p key={note.id}><button style={buttonStyle} onClick={() => !note.read && markRead(note.id)}>{note.read ? 'Read' : 'Mark read'}</button>{note.message}</p>)}</section>
    <section style={sectionStyle}><h2>Support tickets</h2><form onSubmit={sendTicket}><input style={inputStyle} placeholder="Subject" value={ticket.subject} onChange={(e) => setTicket({ ...ticket, subject: e.target.value })} required /><textarea style={inputStyle} placeholder="How can we help?" value={ticket.message} onChange={(e) => setTicket({ ...ticket, message: e.target.value })} required /><select style={inputStyle} value={ticket.priority} onChange={(e) => setTicket({ ...ticket, priority: e.target.value })}><option>NORMAL</option><option>HIGH</option><option>URGENT</option></select><button style={buttonStyle}>Create ticket</button></form>{tickets.map((item) => <p key={item.id}>#{item.id} <b>{item.status}</b>: {item.subject}{item.adminResponse ? ` — Admin: ${item.adminResponse}` : ''}</p>)}</section>
  </main>
}
