import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { apiRequest } from '../services/api'
import PortalShell, { EmptyState, LoadingState, Panel, Status } from '../components/PortalShell'
import './CustomerDashboard.css'

export default function CustomerDashboard() {
  const navigate = useNavigate()
  const token = sessionStorage.getItem('token')
  const [data, setData] = useState(null)
  const [services, setServices] = useState([])
  const [plans, setPlans] = useState([])
  const [entitlements, setEntitlements] = useState([])
  const [payments, setPayments] = useState([])
  const [refunds, setRefunds] = useState([])
  const [paymentMode, setPaymentMode] = useState({ mode: 'payhere', label: 'PayHere Sandbox' })
  const [demoPayment, setDemoPayment] = useState(null)
  const [selectedPlan, setSelectedPlan] = useState(null)
  const [notes, setNotes] = useState([])
  const [tickets, setTickets] = useState([])
  const [profile, setProfile] = useState({ name: '', email: '', town: '', phone: '' })
  const [otp, setOtp] = useState('')
  const [booking, setBooking] = useState({ service_id: '', booking_date: '', booking_time: '' })
  const [ticket, setTicket] = useState({ subject: '', message: '', priority: 'NORMAL' })
  const [complaint, setComplaint] = useState({ subject: '', description: '' })
  const [submittedComplaints, setSubmittedComplaints] = useState([])
  const [message, setMessage] = useState('')
  const [busy, setBusy] = useState(false)

  const load = async () => {
    if (!token) return navigate('/login', { replace: true })
    try {
      const [dashboard, catalogue, planRows, entitlementRows, paymentRows, paymentModeRow, notificationRows, ticketRows, complaintRows, refundRows] = await Promise.all([
        apiRequest('/customer/dashboard', 'GET', null, token), apiRequest('/services'), apiRequest('/subscriptions'), apiRequest('/subscriptions/entitlements', 'GET', null, token), apiRequest('/payments/my', 'GET', null, token), apiRequest('/payments/mode', 'GET', null, token), apiRequest('/notifications', 'GET', null, token), apiRequest('/support/my', 'GET', null, token), apiRequest('/complaints/my', 'GET', null, token), apiRequest('/refunds/my', 'GET', null, token),
      ])
      setData(dashboard); setProfile({ name: dashboard.profile.name || '', email: dashboard.profile.email || '', town: dashboard.profile.town || '', phone: dashboard.profile.phone || '' })
      setServices(catalogue); setPlans(planRows); setEntitlements(entitlementRows.entitlements || entitlementRows); setPayments(paymentRows.payments || []); setPaymentMode(paymentModeRow); setNotes(notificationRows); setTickets(ticketRows); setSubmittedComplaints(complaintRows); setRefunds(refundRows)
    } catch (error) { setMessage(error.message) }
  }
  useEffect(() => { load() }, [])
  const availableServiceIds = useMemo(() => new Set(entitlements.filter((item) => item.remaining_units > 0).map((item) => item.category_id)), [entitlements])
  const submitProfile = async (event) => { event.preventDefault(); setBusy(true); try { await apiRequest('/profile', 'PUT', profile, token); setMessage('Profile saved.'); await load() } catch (error) { setMessage(error.message) } finally { setBusy(false) } }
  const sendOtp = async () => { try { await apiRequest('/profile/phone/send', 'POST', { phone: profile.phone }, token); setMessage('Verification code sent to your phone.') } catch (error) { setMessage(error.message) } }
  const verifyOtp = async () => { try { await apiRequest('/profile/phone/verify', 'POST', { phone: profile.phone, code: otp }, token); setMessage('Phone verified.'); await load() } catch (error) { setMessage(error.message) } }
  const createBooking = async (event) => { event.preventDefault(); setBusy(true); try { const result = await apiRequest('/bookings', 'POST', { ...booking, service_id: Number(booking.service_id) }, token); setMessage(`Booking #${result.booking_id} created (${result.status}). Start PIN: ${result.start_pin}; completion PIN: ${result.completion_pin}`); setBooking({ service_id: '', booking_date: '', booking_time: '' }); await load() } catch (error) { setMessage(error.message) } finally { setBusy(false) } }
  const cancelBooking = async (id) => { const reason = window.prompt('Cancellation reason (at least 3 characters):'); if (!reason) return; try { await apiRequest(`/bookings/${id}/cancel`, 'PUT', { confirmed: true, reason }, token); await load() } catch (error) { setMessage(error.message) } }
  const showPins = async (id) => { try { const pins = await apiRequest(`/bookings/${id}/pins`, 'GET', null, token); setMessage(`Booking #${id} — Start PIN: ${pins.start_pin}; Completion PIN: ${pins.completion_pin}`) } catch (error) { setMessage(error.message) } }
  const cancelMembership = async (id) => { if (!window.confirm('Cancel this membership?')) return; try { await apiRequest(`/subscriptions/${id}/cancel`, 'PUT', { confirmed: true }, token); await load() } catch (error) { setMessage(error.message) } }
  const setAutoRenew = async (id, auto_renew) => { try { await apiRequest(`/subscriptions/${id}/auto-renew`, 'PUT', { auto_renew }, token); await load() } catch (error) { setMessage(error.message) } }
  const reschedule = async (row) => { const booking_date = window.prompt('New date (YYYY-MM-DD)', row.bookingDate); const booking_time = window.prompt('New time', row.bookingTime); const reason = window.prompt('Reason'); if (!booking_date || !booking_time || !reason) return; try { await apiRequest(`/bookings/${row.id}/reschedule`, 'PUT', { booking_date, booking_time, reason, confirmed: true }, token); await load() } catch (error) { setMessage(error.message) } }
  const startPayment = async (plan) => { setBusy(true); try { if (paymentMode.mode === 'demo') { setDemoPayment(await apiRequest('/payments/demo/order', 'POST', { plan_id: plan.id, auto_renew: false }, token)); setBusy(false); return } const order = await apiRequest('/payments/payhere/order', 'POST', { plan_id: plan.id }, token); const form = document.createElement('form'); form.method = 'POST'; form.action = order.checkoutUrl; Object.entries(order.fields).forEach(([name, value]) => { const input = document.createElement('input'); input.type = 'hidden'; input.name = name; input.value = value || ''; form.appendChild(input) }); document.body.appendChild(form); form.submit() } catch (error) { setMessage(error.message); setBusy(false) } }
  const completeDemoPayment = async (outcome) => { if (!demoPayment) return; setBusy(true); try { const result = await apiRequest(`/payments/demo/${demoPayment.payment_id}/complete`, 'POST', { outcome }, token); setMessage(result.message); setDemoPayment(null); await load() } catch (error) { setMessage(error.message) } finally { setBusy(false) } }
  const sendTicket = async (event) => { event.preventDefault(); try { await apiRequest('/support', 'POST', ticket, token); setTicket({ subject: '', message: '', priority: 'NORMAL' }); setMessage('Support ticket created.'); await load() } catch (error) { setMessage(error.message) } }
  const submitComplaint = async (event) => { event.preventDefault(); setBusy(true); try { const result = await apiRequest('/complaints', 'POST', complaint, token); setComplaint({ subject: '', description: '' }); setMessage(result.message); await load(); } catch (error) { setMessage(error.message) } finally { setBusy(false) } }
  const requestRefund = async (subscription) => { const reason = window.prompt(`Optional reason for refunding ${subscription.plan.title}:`) ?? ''; try { await apiRequest('/refunds', 'POST', { subscription_id: subscription.id, reason }, token); setMessage('Refund request submitted for review.'); await load() } catch (error) { setMessage(error.message) } }
  const markRead = async (id) => { try { await apiRequest(`/notifications/${id}/read`, 'PUT', {}, token); await load() } catch (error) { setMessage(error.message) } }
  if (!data) return <LoadingState title={message || 'Preparing your private member portal'} />
  const rows = [...data.upcomingBookings, ...data.pastBookings]
  const planKind = (plan) => plan.entitlements?.length > 1 ? 'Combo package' : 'Individual package'
  const renewalCopy = (plan) => plan.type?.toLowerCase().includes('recurr') ? 'Recurring every 30 days' : 'One-time package'
  const nextBooking = data.upcomingBookings[0]
  return <PortalShell role="Customer" userName={profile.name} title="Customer portal" heroTitle={`Welcome back, ${profile.name?.split(' ')[0] || 'member'}.`} subtitle="Your membership, concierge bookings and support are kept together in one considered place." notice={message} onSignOut={() => { sessionStorage.clear(); navigate('/login') }} navItems={[{ id: 'overview', label: 'Overview' }, { id: 'membership', label: 'Membership' }, { id: 'book', label: 'Book service' }, { id: 'packages', label: 'Packages' }, { id: 'services', label: 'My services' }, { id: 'support', label: 'Support' }, { id: 'profile', label: 'Profile' }]}>
    <div id="overview" className="customer-overview">
      <Panel className="customer-next"><p className="portal-kicker">Your next service</p>{nextBooking ? <><Status tone={String(nextBooking.status).toLowerCase()}>{nextBooking.status}</Status><h2>{nextBooking.service?.title || 'Luxora service'}</h2><p>{new Date(nextBooking.bookingDate).toLocaleDateString(undefined, { weekday: 'long', day: 'numeric', month: 'long' })} · {nextBooking.bookingTime}</p><small>{nextBooking.provider?.user?.name || nextBooking.provider_name || 'A provider will be assigned shortly'}</small></> : <EmptyState title="No service scheduled">When you are ready, reserve your next moment of care below.</EmptyState>}</Panel>
      <Panel className="customer-credit-summary"><p className="portal-kicker">Your Luxora credits</p><div className="credit-summary-grid">{entitlements.length ? entitlements.map((item) => <div key={item.category_id}><span>{item.category_name}</span><strong>{item.remaining_units}</strong><small>of {item.entitled_units} visits available</small></div>) : <EmptyState title="No active credits">Explore a membership designed around the care you need.</EmptyState>}</div></Panel>
    </div>
    <Panel id="membership" className="customer-memberships"><p className="portal-kicker">Membership</p><h2>Care, on your terms.</h2><div className="membership-card-grid">{data.activeSubscriptions.length ? data.activeSubscriptions.map((subscription) => <article className="membership-card" key={subscription.id}><div><Status tone={String(subscription.status).toLowerCase()}>{subscription.status}</Status><h3>{subscription.plan.title}</h3><p>Active until {new Date(subscription.endDate).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' })}</p></div><div className="membership-actions"><button className="ui-button ui-button--secondary" onClick={() => setAutoRenew(subscription.id, !subscription.autoRenew)}>{subscription.autoRenew ? 'Pause renewal' : 'Enable renewal'}</button><button className="ui-button ui-button--text danger" onClick={() => cancelMembership(subscription.id)}>Cancel</button></div></article>) : <EmptyState title="Your membership begins here">Choose a package below to unlock Luxora services.</EmptyState>}</div></Panel>
    <Panel id="book" className="booking-workspace"><p className="portal-kicker">Concierge booking · 01 Service · 02 Date & time · 03 Confirmation</p><h2>Book your next service</h2><form className="luxora-form booking-form" onSubmit={createBooking}><label><span>Service</span><select value={booking.service_id} onChange={(e) => setBooking({ ...booking, service_id: e.target.value })} required><option value="">Select an included service</option>{services.filter((service) => availableServiceIds.has(service.category_id)).map((service) => <option key={service.id} value={service.id}>{service.title} — {service.category_name}</option>)}</select></label><label><span>Preferred date</span><input type="date" value={booking.booking_date} onChange={(e) => setBooking({ ...booking, booking_date: e.target.value })} required /></label><label><span>Preferred time</span><input type="time" value={booking.booking_time} onChange={(e) => setBooking({ ...booking, booking_time: e.target.value })} required /></label><button className="ui-button ui-button--primary" disabled={busy}>Confirm service</button></form></Panel>
    <Panel id="packages" className="package-workspace"><div className="section-heading"><div><p className="portal-kicker">Packages & memberships</p><h2>Exceptional care, selected for you.</h2></div><Status tone={paymentMode.mode === 'demo' ? 'available' : ''}>{paymentMode.mode === 'demo' ? 'Demo payment' : paymentMode.label}</Status></div><div className="package-grid">{plans.length ? plans.map((plan) => <article className="package-card" key={plan.id}><div><Status>{planKind(plan)}</Status><h3>{plan.title}</h3><p>{plan.description || 'A considered Luxora service package.'}</p></div><ul>{plan.entitlements?.map((item) => <li key={item.category_name}><span>{item.category_name}</span><b>{item.units} visits</b></li>)}</ul><div className="package-card-footer"><span><b>LKR {Number(plan.priceMonthly).toLocaleString()}</b><small>{plan.durationDays} days · {renewalCopy(plan)}</small></span><button className="ui-button ui-button--secondary" disabled={busy || plan.active === false} onClick={() => setSelectedPlan(plan)}>View package</button></div></article>) : <EmptyState title="Packages are being curated">Please return shortly to see available Luxora care.</EmptyState>}</div>{selectedPlan && <div className="purchase-drawer"><div><p className="portal-kicker">Selected package</p><h3>{selectedPlan.title}</h3><p>{selectedPlan.entitlements?.map((item) => `${item.category_name}: ${item.units}`).join(' · ')}</p></div><b>LKR {Number(selectedPlan.priceMonthly).toLocaleString()}</b><button className="ui-button ui-button--primary" disabled={busy} onClick={() => startPayment(selectedPlan)}>{paymentMode.mode === 'demo' ? 'Open demo checkout' : 'Continue to checkout'}</button><button className="ui-button ui-button--text" onClick={() => setSelectedPlan(null)}>Close</button></div>}{demoPayment && <div className="demo-checkout"><div><p className="portal-kicker">Demo payment</p><h3>{demoPayment.plan.title}</h3><p>{demoPayment.plan.currency} {demoPayment.plan.amount} · No real money is charged.</p></div><div><button className="ui-button ui-button--primary" disabled={busy} onClick={() => completeDemoPayment('success')}>Simulate success</button><button className="ui-button ui-button--secondary" disabled={busy} onClick={() => completeDemoPayment('failure')}>Simulate failure</button><button className="ui-button ui-button--text" disabled={busy} onClick={() => completeDemoPayment('cancel')}>Cancel</button></div></div>}</Panel>
    <Panel id="services"><p className="portal-kicker">My services</p><h2>Your service history</h2><div className="service-list">{rows.length ? rows.map((row) => <article key={row.id} className="service-row"><div className="service-time"><b>{row.bookingTime}</b><small>{new Date(row.bookingDate).toLocaleDateString(undefined, { day: 'numeric', month: 'short' })}</small></div><div><Status tone={String(row.status).toLowerCase()}>{row.status}</Status><h3>{row.service?.title || 'Luxora service'}</h3><p>{row.provider?.user?.name || row.provider_name || 'Awaiting provider assignment'}</p></div><div className="service-row-actions">{!['CANCELLED', 'COMPLETED'].includes(row.status) && <button className="ui-button ui-button--text" onClick={() => showPins(row.id)}>View PINs</button>}{['PENDING', 'ASSIGNED'].includes(row.status) && <><button className="ui-button ui-button--secondary" onClick={() => reschedule(row)}>Reschedule</button><button className="ui-button ui-button--text danger" onClick={() => cancelBooking(row.id)}>Cancel</button></>}</div></article>) : <EmptyState title="No services yet">Your booked services will appear here with their live status.</EmptyState>}</div><h3>Payment history</h3><div className="payment-history">{payments.length ? payments.map((payment) => <p key={payment.id}><Status tone={String(payment.status).toLowerCase()}>{payment.status}</Status><span>{payment.plan?.title || 'Luxora package'} · {payment.gateway}</span><b>{payment.expectedCurrency} {payment.expectedAmount}</b></p>) : <p className="quiet-copy">Your package payments will appear here.</p>}</div></Panel>
    <Panel id="support"><p className="portal-kicker">Help & support</p><h2>We are here when you need us.</h2><div className="support-columns"><div><h3>Refunds</h3>{refunds.length ? refunds.map((item) => <article className="support-record" key={item.id}><Status tone={item.refundRequest?.status?.toLowerCase() || (item.eligible ? 'available' : 'cancelled')}>{item.refundRequest?.status || (item.eligible ? 'Eligible' : 'Not eligible')}</Status><b>{item.plan.title}</b><p>{item.used_units} visits used · {item.plan.entitlements.map((e) => `${e.category.name}: ${e.units}`).join(' · ')}</p>{item.eligible && <button className="ui-button ui-button--secondary" onClick={() => requestRefund(item)}>Request refund</button>}{item.refundRequest?.adminNote && <small>Note: {item.refundRequest.adminNote}</small>}</article>) : <EmptyState title="No purchases to review">Your refunds and package purchases will appear here.</EmptyState>}</div><div><h3>Support request</h3><form className="luxora-form" onSubmit={sendTicket}><label><span>Subject</span><input value={ticket.subject} onChange={(e) => setTicket({ ...ticket, subject: e.target.value })} required /></label><label><span>How can we help?</span><textarea value={ticket.message} onChange={(e) => setTicket({ ...ticket, message: e.target.value })} required /></label><label><span>Priority</span><select value={ticket.priority} onChange={(e) => setTicket({ ...ticket, priority: e.target.value })}><option>NORMAL</option><option>HIGH</option><option>URGENT</option></select></label><button className="ui-button ui-button--primary">Send request</button></form>{tickets.map((item) => <p className="support-ticket" key={item.id}><Status tone={item.status?.toLowerCase()}>{item.status}</Status> {item.subject}{item.adminResponse ? ` — ${item.adminResponse}` : ''}</p>)}</div></div></Panel>
    <Panel id="profile" className="profile-workspace"><p className="portal-kicker">Profile & preferences</p><h2>Your Luxora details</h2><form className="luxora-form profile-form" onSubmit={submitProfile}><label><span>Name</span><input value={profile.name} onChange={(e) => setProfile({ ...profile, name: e.target.value })} required /></label><label><span>Email</span><input type="email" value={profile.email} onChange={(e) => setProfile({ ...profile, email: e.target.value })} required /></label><label><span>Service town</span><input value={profile.town} onChange={(e) => setProfile({ ...profile, town: e.target.value })} /></label><label><span>Phone (E.164)</span><input value={profile.phone} onChange={(e) => setProfile({ ...profile, phone: e.target.value })} placeholder="+94771234567" /></label><button className="ui-button ui-button--primary" disabled={busy}>Save profile</button></form><div className="phone-verification"><button className="ui-button ui-button--secondary" onClick={sendOtp}>Send verification code</button><input value={otp} onChange={(e) => setOtp(e.target.value)} placeholder="Enter code" aria-label="Verification code" /><button className="ui-button ui-button--secondary" onClick={verifyOtp}>Verify phone</button></div><div className="customer-activity"><h3>Notifications</h3>{notes.length ? notes.map((note) => <button key={note.id} className={`notification-row ${note.read ? '' : 'is-unread'}`} onClick={() => !note.read && markRead(note.id)}>{note.message}<small>{note.read ? 'Read' : 'Mark as read'}</small></button>) : <p className="quiet-copy">There are no new notifications.</p>}<h3>Complaints</h3><form className="luxora-form" onSubmit={submitComplaint}><input placeholder="Subject" value={complaint.subject} onChange={(e) => setComplaint({ ...complaint, subject: e.target.value })} required maxLength={150} /><textarea placeholder="Describe the issue" value={complaint.description} onChange={(e) => setComplaint({ ...complaint, description: e.target.value })} required maxLength={2000} /><button className="ui-button ui-button--secondary" disabled={busy}>Submit complaint</button></form>{submittedComplaints.map((item) => <p className="support-ticket" key={item.id}><Status tone={item.status?.toLowerCase()}>{item.status}</Status> {item.subject}{item.admin_note ? ` — ${item.admin_note}` : ''}</p>)}</div></Panel>
  </PortalShell>
}
