import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { apiRequest } from '../services/api'
import PortalShell, { EmptyState, LoadingState, Panel, Status } from '../components/PortalShell'
import { ConfirmDialog, FilterPills, Modal, PromptDialog, SearchInput } from '../components/ui'
import './CustomerDashboard.css'

const CATEGORY_GLYPHS = ['◈', '❦', '♢', '▣', '◌', '○']
const emptyWizard = { step: 1, category: null, service_id: '', booking_date: '', booking_time: '' }

export default function CustomerDashboard() {
  const navigate = useNavigate()
  const token = sessionStorage.getItem('token')
  const [data, setData] = useState(null)
  const [services, setServices] = useState([])
  const [plans, setPlans] = useState([])
  const [entitlements, setEntitlements] = useState([])
  const [payments, setPayments] = useState([])
  const [refunds, setRefunds] = useState([])
  const [paymentMode, setPaymentMode] = useState({ mode: 'payhere', label: 'PayHere Sandbox' })
  const [demoPayment, setDemoPayment] = useState(null)
  const [selectedPlan, setSelectedPlan] = useState(null)
  const [notes, setNotes] = useState([])
  const [tickets, setTickets] = useState([])
  const [profile, setProfile] = useState({ name: '', email: '', town: '', phone: '' })
  const [otp, setOtp] = useState('')
  const [wizard, setWizard] = useState(emptyWizard)
  const [ticket, setTicket] = useState({ subject: '', message: '', priority: 'NORMAL' })
  const [complaint, setComplaint] = useState({ subject: '', description: '' })
  const [submittedComplaints, setSubmittedComplaints] = useState([])
  const [message, setMessage] = useState('')
  const [busy, setBusy] = useState(false)
  const [dialog, setDialog] = useState(null)
  const [serviceSearch, setServiceSearch] = useState('')
  const [serviceFilter, setServiceFilter] = useState('all')
  const [paymentFilter, setPaymentFilter] = useState('all')

  const load = async () => {
    if (!token) return navigate('/login', { replace: true })
    try {
      const [dashboard, catalogue, planRows, entitlementRows, paymentRows, paymentModeRow, notificationRows, ticketRows, complaintRows, refundRows] = await Promise.all([
        apiRequest('/customer/dashboard', 'GET', null, token), apiRequest('/services'), apiRequest('/subscriptions'), apiRequest('/subscriptions/entitlements', 'GET', null, token), apiRequest('/payments/my', 'GET', null, token), apiRequest('/payments/mode', 'GET', null, token), apiRequest('/notifications', 'GET', null, token), apiRequest('/support/my', 'GET', null, token), apiRequest('/complaints/my', 'GET', null, token), apiRequest('/refunds/my', 'GET', null, token),
      ])
      setData(dashboard); setProfile({ name: dashboard.profile.name || '', email: dashboard.profile.email || '', town: dashboard.profile.town || '', phone: dashboard.profile.phone || '' })
      setServices(catalogue); setPlans(planRows); setEntitlements(entitlementRows.entitlements || entitlementRows); setPayments(paymentRows.payments || []); setPaymentMode(paymentModeRow); setNotes(notificationRows); setTickets(ticketRows); setSubmittedComplaints(complaintRows); setRefunds(refundRows)
    } catch (error) { setMessage(error.message) }
  }
  useEffect(() => { load() }, [])
  const bookableCategories = useMemo(() => entitlements.filter((item) => item.remaining_units > 0), [entitlements])
  const submitProfile = async (event) => { event.preventDefault(); setBusy(true); try { await apiRequest('/profile', 'PUT', profile, token); setMessage('Profile saved.'); await load() } catch (error) { setMessage(error.message) } finally { setBusy(false) } }
  const sendOtp = async () => { try { await apiRequest('/profile/phone/send', 'POST', { phone: profile.phone }, token); setMessage('Verification code sent to your phone.') } catch (error) { setMessage(error.message) } }
  const verifyOtp = async () => { try { await apiRequest('/profile/phone/verify', 'POST', { phone: profile.phone, code: otp }, token); setMessage('Phone verified.'); await load() } catch (error) { setMessage(error.message) } }
  const wizardServices = wizard.category ? services.filter((service) => service.category_id === wizard.category.category_id) : []
  const confirmWizard = async () => { setBusy(true); try { const result = await apiRequest('/bookings', 'POST', { service_id: Number(wizard.service_id), booking_date: wizard.booking_date, booking_time: wizard.booking_time }, token); setWizard(emptyWizard); setDialog({ type: 'confirmed', result }); await load() } catch (error) { setMessage(error.message) } finally { setBusy(false) } }
  const cancelBooking = async (values) => { try { await apiRequest(`/bookings/${dialog.row.id}/cancel`, 'PUT', { confirmed: true, reason: values.reason }, token); setDialog(null); await load() } catch (error) { setMessage(error.message); setDialog(null) } }
  const showPins = async (id) => { try { const pins = await apiRequest(`/bookings/${id}/pins`, 'GET', null, token); setDialog({ type: 'pins', pins, id }) } catch (error) { setMessage(error.message) } }
  const cancelMembership = async () => { try { await apiRequest(`/subscriptions/${dialog.row.id}/cancel`, 'PUT', { confirmed: true }, token); setDialog(null); await load() } catch (error) { setMessage(error.message); setDialog(null) } }
  const setAutoRenew = async (id, auto_renew) => { try { await apiRequest(`/subscriptions/${id}/auto-renew`, 'PUT', { auto_renew }, token); await load() } catch (error) { setMessage(error.message) } }
  const reschedule = async (values) => { const row = dialog.row; try { await apiRequest(`/bookings/${row.id}/reschedule`, 'PUT', { booking_date: values.booking_date, booking_time: values.booking_time, reason: values.reason, confirmed: true }, token); setDialog(null); await load() } catch (error) { setMessage(error.message); setDialog(null) } }
  const startPayment = async (plan) => { setBusy(true); try { if (paymentMode.mode === 'demo') { setDemoPayment(await apiRequest('/payments/demo/order', 'POST', { plan_id: plan.id, auto_renew: false }, token)); setBusy(false); return } const order = await apiRequest('/payments/payhere/order', 'POST', { plan_id: plan.id }, token); const form = document.createElement('form'); form.method = 'POST'; form.action = order.checkoutUrl; Object.entries(order.fields).forEach(([name, value]) => { const input = document.createElement('input'); input.type = 'hidden'; input.name = name; input.value = value || ''; form.appendChild(input) }); document.body.appendChild(form); form.submit() } catch (error) { setMessage(error.message); setBusy(false) } }
  const completeDemoPayment = async (outcome) => { if (!demoPayment) return; setBusy(true); try { const result = await apiRequest(`/payments/demo/${demoPayment.payment_id}/complete`, 'POST', { outcome }, token); setMessage(result.message); setDemoPayment(null); await load() } catch (error) { setMessage(error.message) } finally { setBusy(false) } }
  const sendTicket = async (event) => { event.preventDefault(); try { await apiRequest('/support', 'POST', ticket, token); setTicket({ subject: '', message: '', priority: 'NORMAL' }); setMessage('Support ticket created.'); await load() } catch (error) { setMessage(error.message) } }
  const submitComplaint = async (event) => { event.preventDefault(); setBusy(true); try { const result = await apiRequest('/complaints', 'POST', complaint, token); setComplaint({ subject: '', description: '' }); setMessage(result.message); await load(); } catch (error) { setMessage(error.message) } finally { setBusy(false) } }
  const requestRefund = async (values) => { try { await apiRequest('/refunds', 'POST', { subscription_id: dialog.row.id, reason: values.reason || '' }, token); setMessage('Refund request submitted for review.'); setDialog(null); await load() } catch (error) { setMessage(error.message); setDialog(null) } }
  const markRead = async (id) => { try { await apiRequest(`/notifications/${id}/read`, 'PUT', {}, token); await load() } catch (error) { setMessage(error.message) } }
  if (!data) return <LoadingState title={message || 'Preparing your private member portal'} />
  const rows = [...data.upcomingBookings, ...data.pastBookings]
  const searched = serviceSearch.trim() ? rows.filter((row) => [row.service?.title, row.provider?.user?.name, row.provider_name, `#${row.id}`, row.bookingDate].filter(Boolean).join(' ').toLowerCase().includes(serviceSearch.trim().toLowerCase())) : rows
  const statusCounts = searched.reduce((counts, row) => { const key = String(row.status).toLowerCase(); counts[key] = (counts[key] || 0) + 1; return counts }, {})
  const filteredRows = serviceFilter === 'all' ? searched : searched.filter((row) => String(row.status).toLowerCase() === serviceFilter)
  const filteredPayments = paymentFilter === 'all' ? payments : payments.filter((payment) => String(payment.status).toLowerCase() === paymentFilter)
  const planKind = (plan) => plan.entitlements?.length > 1 ? 'Combo package' : 'Individual package'
  const renewalCopy = (plan) => plan.type?.toLowerCase().includes('recurr') ? 'Recurring every 30 days' : 'One-time package'
  const nextBooking = data.upcomingBookings[0]
  const wizardService = services.find((service) => service.id === Number(wizard.service_id))
  return <PortalShell role="Customer" userName={profile.name} title="Customer portal" heroTitle={`Welcome back, ${profile.name?.split(' ')[0] || 'member'}.`} subtitle="Your membership, concierge bookings and support are kept together in one considered place." notice={message} onSignOut={() => { sessionStorage.clear(); navigate('/login') }} navItems={[{ id: 'overview', label: 'Overview' }, { id: 'membership', label: 'Membership' }, { id: 'book', label: 'Book service' }, { id: 'packages', label: 'Packages' }, { id: 'services', label: 'My services' }, { id: 'support', label: 'Support' }, { id: 'profile', label: 'Profile' }]}>
    <div id="overview" className="customer-overview">
      <Panel className="customer-next"><p className="portal-kicker">Your next service</p>{nextBooking ? <><Status tone={String(nextBooking.status).toLowerCase()}>{nextBooking.status}</Status><h2>{nextBooking.service?.title || 'Luxora service'}</h2><p>{new Date(nextBooking.bookingDate).toLocaleDateString(undefined, { weekday: 'long', day: 'numeric', month: 'long' })} · {nextBooking.bookingTime}</p><small>{nextBooking.provider?.user?.name || nextBooking.provider_name || 'A provider will be assigned shortly'}</small></> : <EmptyState title="No service scheduled">When you are ready, reserve your next moment of care below.</EmptyState>}</Panel>
      <Panel className="customer-credit-summary"><p className="portal-kicker">Your Luxora credits</p><div className="credit-summary-grid">{entitlements.length ? entitlements.map((item) => <div key={item.category_id}><span>{item.category_name}</span><strong>{item.remaining_units}</strong><small>of {item.entitled_units} visits available</small></div>) : <EmptyState title="No active credits">Explore a membership designed around the care you need.</EmptyState>}</div></Panel>
    </div>
    <Panel id="membership" className="customer-memberships"><p className="portal-kicker">Membership</p><h2>Care, on your terms.</h2><div className="membership-card-grid">{data.activeSubscriptions.length ? data.activeSubscriptions.map((subscription) => <article className="membership-card" key={subscription.id}><div><Status tone={String(subscription.status).toLowerCase()}>{subscription.status}</Status><h3>{subscription.plan.title}</h3><p>Active until {new Date(subscription.endDate).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' })}</p></div><div className="membership-actions"><button className="ui-button ui-button--secondary" onClick={() => setAutoRenew(subscription.id, !subscription.autoRenew)}>{subscription.autoRenew ? 'Pause renewal' : 'Enable renewal'}</button><button className="ui-button ui-button--text danger" onClick={() => setDialog({ type: 'cancelMembership', row: subscription })}>Cancel</button></div></article>) : <EmptyState title="Your membership begins here">Choose a package below to unlock Luxora services.</EmptyState>}</div></Panel>
    <Panel id="book" className="booking-workspace"><p className="portal-kicker">Concierge booking · 01 Service · 02 Date & time · 03 Confirmation</p><h2>Book your next service</h2>
      <div className="booking-wizard">
        <div className="wizard-steps"><span className={wizard.step === 1 ? 'is-active' : ''}>01 · Category</span><span className={wizard.step === 2 ? 'is-active' : ''}>02 · Date & time</span><span className={wizard.step === 3 ? 'is-active' : ''}>03 · Confirm</span></div>
        {wizard.step === 1 && (bookableCategories.length
          ? <div className="wizard-category-grid">{bookableCategories.map((item, index) => <button key={item.category_id} type="button" className={`wizard-category ${wizard.category?.category_id === item.category_id ? 'is-selected' : ''}`} onClick={() => setWizard({ ...wizard, category: item, service_id: '' })}><i aria-hidden="true">{CATEGORY_GLYPHS[index % CATEGORY_GLYPHS.length]}</i><b>{item.category_name}</b><small>{item.remaining_units} of {item.entitled_units} visits available</small></button>)}</div>
          : <EmptyState title="No credits available">Purchase a package below to unlock concierge services.</EmptyState>)}
        {wizard.step === 2 && <div className="luxora-form booking-form">
          <label><span>Service</span><select value={wizard.service_id} onChange={(event) => setWizard({ ...wizard, service_id: event.target.value })}><option value="">Select a service</option>{wizardServices.map((service) => <option key={service.id} value={service.id}>{service.title}</option>)}</select></label>
          <label><span>Preferred date</span><input type="date" min={new Date().toISOString().slice(0, 10)} value={wizard.booking_date} onChange={(event) => setWizard({ ...wizard, booking_date: event.target.value })} /></label>
          <label><span>Preferred time</span><input type="time" value={wizard.booking_time} onChange={(event) => setWizard({ ...wizard, booking_time: event.target.value })} /></label>
        </div>}
        {wizard.step === 3 && <div className="wizard-review">
          <div><span>Service</span><b>{wizardService?.title || '—'}</b></div>
          <div><span>Category</span><b>{wizard.category?.category_name}</b></div>
          <div><span>Date</span><b>{wizard.booking_date ? new Date(`${wizard.booking_date}T00:00`).toLocaleDateString(undefined, { weekday: 'long', day: 'numeric', month: 'long' }) : '—'}</b></div>
          <div><span>Time</span><b>{wizard.booking_time || '—'}</b></div>
          <div><span>Credits after booking</span><b>{wizard.category ? `${wizard.category.remaining_units - 1} ${wizard.category.category_name} visits remaining` : '—'}</b></div>
        </div>}
        <div className="wizard-actions">
          {wizard.step > 1 && <button className="ui-button ui-button--text" onClick={() => setWizard({ ...wizard, step: wizard.step - 1 })}>← Back</button>}
          {wizard.step === 1 && wizard.category && <button className="ui-button ui-button--primary" onClick={() => setWizard({ ...wizard, step: 2 })}>Continue →</button>}
          {wizard.step === 2 && <button className="ui-button ui-button--primary" disabled={!wizard.service_id || !wizard.booking_date || !wizard.booking_time} onClick={() => setWizard({ ...wizard, step: 3 })}>Review booking →</button>}
          {wizard.step === 3 && <button className="ui-button ui-button--primary" disabled={busy} onClick={confirmWizard}>Confirm service ✓</button>}
        </div>
      </div>
    </Panel>
    <Panel id="packages" className="package-workspace"><div className="section-heading"><div><p className="portal-kicker">Packages & memberships</p><h2>Exceptional care, selected for you.</h2></div><Status tone={paymentMode.mode === 'demo' ? 'available' : ''}>{paymentMode.mode === 'demo' ? 'Demo payment' : paymentMode.label}</Status></div><div className="package-grid">{plans.length ? plans.map((plan) => <article className="package-card" key={plan.id}><div><Status>{planKind(plan)}</Status><h3>{plan.title}</h3><p>{plan.description || 'A considered Luxora service package.'}</p></div><ul>{plan.entitlements?.map((item) => <li key={item.category_name}><span>{item.category_name}</span><b>{item.units} visits</b></li>)}</ul><div className="package-card-footer"><span><b>LKR {Number(plan.priceMonthly).toLocaleString()}</b><small>{plan.durationDays} days · {renewalCopy(plan)}</small></span><button className="ui-button ui-button--secondary" disabled={busy || plan.active === false} onClick={() => setSelectedPlan(plan)}>View package</button></div></article>) : <EmptyState title="Packages are being curated">Please return shortly to see available Luxora care.</EmptyState>}</div>{selectedPlan && <div className="purchase-drawer"><div><p className="portal-kicker">Selected package</p><h3>{selectedPlan.title}</h3><p>{selectedPlan.entitlements?.map((item) => `${item.category_name}: ${item.units}`).join(' · ')}</p></div><b>LKR {Number(selectedPlan.priceMonthly).toLocaleString()}</b><button className="ui-button ui-button--primary" disabled={busy} onClick={() => startPayment(selectedPlan)}>{paymentMode.mode === 'demo' ? 'Open demo checkout' : 'Continue to checkout'}</button><button className="ui-button ui-button--text" onClick={() => setSelectedPlan(null)}>Close</button></div>}{demoPayment && <div className="demo-checkout"><div><p className="portal-kicker">Demo payment</p><h3>{demoPayment.plan.title}</h3><p>{demoPayment.plan.currency} {demoPayment.plan.amount} · No real money is charged.</p></div><div><button className="ui-button ui-button--primary" disabled={busy} onClick={() => completeDemoPayment('success')}>Simulate success</button><button className="ui-button ui-button--secondary" disabled={busy} onClick={() => completeDemoPayment('failure')}>Simulate failure</button><button className="ui-button ui-button--text" disabled={busy} onClick={() => completeDemoPayment('cancel')}>Cancel</button></div></div>}</Panel>
    <Panel id="services"><div className="section-heading"><div><p className="portal-kicker">My services</p><h2>Your service history</h2></div><SearchInput value={serviceSearch} onChange={setServiceSearch} placeholder="Search service, provider or #id" ariaLabel="Search service history" /></div><FilterPills ariaLabel="Filter by status" value={serviceFilter} onChange={setServiceFilter} options={[{ value: 'all', label: 'All', count: searched.length }, ...Object.entries(statusCounts).map(([status, count]) => ({ value: status, label: status.replace('_', ' '), count }))]} /><div className="service-list">{filteredRows.length ? filteredRows.map((row) => <article key={row.id} className="service-row"><div className="service-time"><b>{row.bookingTime}</b><small>{new Date(row.bookingDate).toLocaleDateString(undefined, { day: 'numeric', month: 'short' })}</small></div><div><Status tone={String(row.status).toLowerCase()}>{row.status}</Status><h3>{row.service?.title || 'Luxora service'}</h3><p>{row.provider?.user?.name || row.provider_name || 'Awaiting provider assignment'}</p></div><div className="service-row-actions">{!['CANCELLED', 'COMPLETED'].includes(row.status) && <button className="ui-button ui-button--text" onClick={() => showPins(row.id)}>View PINs</button>}{['PENDING', 'ASSIGNED'].includes(row.status) && <><button className="ui-button ui-button--secondary" onClick={() => setDialog({ type: 'reschedule', row })}>Reschedule</button><button className="ui-button ui-button--text danger" onClick={() => setDialog({ type: 'cancelBooking', row })}>Cancel</button></>}</div></article>) : <EmptyState title="No services match">Adjust the search or filter to see your booked services.</EmptyState>}</div><h3>Payment history</h3><FilterPills ariaLabel="Filter payments" value={paymentFilter} onChange={setPaymentFilter} options={[{ value: 'all', label: 'All', count: payments.length }, ...['completed', 'refunded', 'failed', 'pending'].filter((status) => payments.some((payment) => String(payment.status).toLowerCase() === status)).map((status) => ({ value: status, label: status, count: payments.filter((payment) => String(payment.status).toLowerCase() === status).length }))]} /><div className="payment-history">{filteredPayments.length ? filteredPayments.map((payment) => <p key={payment.id}><Status tone={String(payment.status).toLowerCase()}>{payment.status}</Status><span>{payment.plan?.title || 'Luxora package'} · {payment.gateway}</span><b>{payment.expectedCurrency} {Number(payment.expectedAmount).toLocaleString()}</b><button className="ui-button ui-button--text" onClick={() => setDialog({ type: 'receipt', row: payment })}>Receipt</button></p>) : <p className="quiet-copy">No payments match this filter.</p>}</div></Panel>
    <Panel id="support"><p className="portal-kicker">Help & support</p><h2>We are here when you need us.</h2><div className="support-columns"><div><h3>Refunds</h3>{refunds.length ? refunds.map((item) => <article className="support-record" key={item.id}><Status tone={item.refundRequest?.status?.toLowerCase() || (item.eligible ? 'available' : 'cancelled')}>{item.refundRequest?.status || (item.eligible ? 'Eligible' : 'Not eligible')}</Status><b>{item.plan.title}</b><p>{item.used_units} visits used · {item.plan.entitlements.map((e) => `${e.category.name}: ${e.units}`).join(' · ')}</p>{item.eligible && <button className="ui-button ui-button--secondary" onClick={() => setDialog({ type: 'refund', row: item })}>Request refund</button>}{item.refundRequest?.adminNote && <small>Note: {item.refundRequest.adminNote}</small>}</article>) : <EmptyState title="No purchases to review">Your refunds and package purchases will appear here.</EmptyState>}</div><div><h3>Support request</h3><form className="luxora-form" onSubmit={sendTicket}><label><span>Subject</span><input value={ticket.subject} onChange={(e) => setTicket({ ...ticket, subject: e.target.value })} required /></label><label><span>How can we help?</span><textarea value={ticket.message} onChange={(e) => setTicket({ ...ticket, message: e.target.value })} required /></label><label><span>Priority</span><select value={ticket.priority} onChange={(e) => setTicket({ ...ticket, priority: e.target.value })}><option>NORMAL</option><option>HIGH</option><option>URGENT</option></select></label><button className="ui-button ui-button--primary">Send request</button></form>{tickets.map((item) => <p className="support-ticket" key={item.id}><Status tone={item.status?.toLowerCase()}>{item.status}</Status> {item.subject}{item.adminResponse ? ` — ${item.adminResponse}` : ''}</p>)}</div></div></Panel>
    <Panel id="profile" className="profile-workspace"><p className="portal-kicker">Profile & preferences</p><h2>Your Luxora details</h2><form className="luxora-form profile-form" onSubmit={submitProfile}><label><span>Name</span><input value={profile.name} onChange={(e) => setProfile({ ...profile, name: e.target.value })} required /></label><label><span>Email</span><input type="email" value={profile.email} onChange={(e) => setProfile({ ...profile, email: e.target.value })} required /></label><label><span>Service town</span><input value={profile.town} onChange={(e) => setProfile({ ...profile, town: e.target.value })} /></label><label><span>Phone (E.164)</span><input value={profile.phone} onChange={(e) => setProfile({ ...profile, phone: e.target.value })} placeholder="+94771234567" /></label><button className="ui-button ui-button--primary" disabled={busy}>Save profile</button></form><div className="phone-verification"><button className="ui-button ui-button--secondary" onClick={sendOtp}>Send verification code</button><input value={otp} onChange={(e) => setOtp(e.target.value)} placeholder="Enter code" aria-label="Verification code" /><button className="ui-button ui-button--secondary" onClick={verifyOtp}>Verify phone</button></div><div className="customer-activity"><h3>Notifications</h3>{notes.length ? notes.map((note) => <button key={note.id} className={`notification-row ${note.read ? '' : 'is-unread'}`} onClick={() => !note.read && markRead(note.id)}>{note.message}<small>{note.read ? 'Read' : 'Mark as read'}</small></button>) : <p className="quiet-copy">There are no new notifications.</p>}<h3>Complaints</h3><form className="luxora-form" onSubmit={submitComplaint}><input placeholder="Subject" value={complaint.subject} onChange={(e) => setComplaint({ ...complaint, subject: e.target.value })} required maxLength={150} /><textarea placeholder="Describe the issue" value={complaint.description} onChange={(e) => setComplaint({ ...complaint, description: e.target.value })} required maxLength={2000} /><button className="ui-button ui-button--secondary" disabled={busy}>Submit complaint</button></form>{submittedComplaints.map((item) => <p className="support-ticket" key={item.id}><Status tone={item.status?.toLowerCase()}>{item.status}</Status> {item.subject}{item.admin_note ? ` — ${item.admin_note}` : ''}</p>)}</div></Panel>

    {dialog?.type === 'confirmed' && <Modal kicker="Booking confirmed" title="Your service is reserved" onClose={() => setDialog(null)} footer={<button className="ui-button ui-button--primary" onClick={() => setDialog(null)}>Great, got it</button>}>
      <p>Booking <b>#{dialog.result.booking_id}</b> is <b>{String(dialog.result.status).toLowerCase()}</b>. Keep these PINs handy — your provider will ask for them.</p>
      <div className="pin-display"><div><span>Start PIN</span><b>{dialog.result.start_pin}</b></div><div><span>Completion PIN</span><b>{dialog.result.completion_pin}</b></div></div>
    </Modal>}
    {dialog?.type === 'pins' && <Modal kicker={`Booking #${dialog.id}`} title="Your verification PINs" onClose={() => setDialog(null)} footer={<button className="ui-button ui-button--primary" onClick={() => setDialog(null)}>Close</button>}>
      <div className="pin-display"><div><span>Start PIN</span><b>{dialog.pins.start_pin}</b></div><div><span>Completion PIN</span><b>{dialog.pins.completion_pin}</b></div></div>
    </Modal>}
    {dialog?.type === 'cancelBooking' && <PromptDialog kicker={`Booking #${dialog.row.id}`} title="Cancel this service?" submitLabel="Cancel booking" fields={[{ name: 'reason', label: 'Reason (optional)', type: 'textarea', initial: '', placeholder: 'Tell us why you are cancelling', maxLength: 500, full: true }]} onSubmit={cancelBooking} onClose={() => setDialog(null)} />}
    {dialog?.type === 'cancelMembership' && <ConfirmDialog danger title="Cancel membership?" message={`Your ${dialog.row.plan.title} membership will end and remaining credits will lapse. This cannot be undone.`} confirmLabel="Cancel membership" onConfirm={cancelMembership} onClose={() => setDialog(null)} />}
    {dialog?.type === 'reschedule' && <PromptDialog kicker={`Booking #${dialog.row.id}`} title="Reschedule service" submitLabel="Reschedule" fields={[{ name: 'booking_date', label: 'New date', type: 'date', required: true, initial: dialog.row.bookingDate }, { name: 'booking_time', label: 'New time', type: 'time', required: true, initial: dialog.row.bookingTime }, { name: 'reason', label: 'Reason', type: 'textarea', required: true, initial: '', placeholder: 'Share a short reason (min 3 characters)', maxLength: 500, full: true }]} onSubmit={reschedule} onClose={() => setDialog(null)} />}
    {dialog?.type === 'refund' && <PromptDialog kicker={dialog.row.plan.title} title="Request a refund" submitLabel="Submit request" fields={[{ name: 'reason', label: 'Reason (optional)', type: 'textarea', initial: '', placeholder: 'Anything the team should know?', maxLength: 1000, full: true, hint: 'Only completely unused packages are eligible for refund.' }]} onSubmit={requestRefund} onClose={() => setDialog(null)} />}
    {dialog?.type === 'receipt' && (() => { const payment = dialog.row; return <Modal printTarget onClose={() => setDialog(null)} footer={<button className="ui-button ui-button--primary" onClick={() => window.print()}>Print receipt</button>}>
      <div className="ui-receipt">
        <div className="ui-receipt-head"><div><b>LUXORA</b><small>Home concierge · Tax invoice</small></div><small>#{payment.gatewayOrderId || `PAY-${payment.id}`}<br />{payment.createdAt ? new Date(payment.createdAt).toLocaleDateString(undefined, { day: 'numeric', month: 'long', year: 'numeric' }) : ''}</small></div>
        <dl>
          <div><dt>Customer</dt><dd>{profile.name}</dd></div>
          <div><dt>Email</dt><dd>{profile.email}</dd></div>
          <div><dt>Package</dt><dd>{payment.plan?.title || 'Luxora package'}</dd></div>
          <div><dt>Gateway</dt><dd>{payment.gateway}</dd></div>
          {payment.subscription?.startDate && <div><dt>Coverage</dt><dd>{new Date(payment.subscription.startDate).toLocaleDateString()} – {payment.subscription.endDate ? new Date(payment.subscription.endDate).toLocaleDateString() : ''}</dd></div>}
          <div><dt>Status</dt><dd>{String(payment.status).toLowerCase()}</dd></div>
        </dl>
        <div className="ui-receipt-total"><span>Total paid</span><b>{payment.expectedCurrency} {Number(payment.capturedAmount ?? payment.expectedAmount).toLocaleString()}</b></div>
      </div>
    </Modal> })()}
  </PortalShell>
}
