import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { apiRequest } from '../services/api'
import './ProviderDashboard.css'

const panel = { background: '#151515', border: '1px solid #333', borderRadius: 12, padding: '1rem', marginBottom: '1rem' }
const button = { padding: '.55rem .8rem', border: 0, borderRadius: 6, background: '#c9a84c', color: '#111', fontWeight: 700, cursor: 'pointer', marginRight: '.4rem' }

export default function ProviderDashboard() {
  const navigate = useNavigate(); const token = sessionStorage.getItem('token')
  const [availability, setAvailability] = useState('available'); const [bookings, setBookings] = useState([]); const [earnings, setEarnings] = useState({ earnings: 0, completedJobs: 0, history: [] }); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  const [scheduleDate, setScheduleDate] = useState(() => new Date().toISOString().slice(0, 10))
  const load = async () => { if (!token) return navigate('/login', { replace: true }); try { const [availabilityRow, bookingRows, earningRow] = await Promise.all([apiRequest('/provider/availability', 'GET', null, token), apiRequest('/bookings/assigned', 'GET', null, token), apiRequest('/provider/earnings', 'GET', null, token)]); setAvailability(availabilityRow.availability_status); setBookings(bookingRows); setEarnings(earningRow) } catch (error) { setMessage(error.message) } }
  useEffect(() => { load() }, [])
  const saveAvailability = async () => { setBusy(true); try { await apiRequest('/provider/availability', 'PUT', { availability_status: availability }, token); setMessage('Availability saved.'); await load() } catch (error) { setMessage(error.message) } finally { setBusy(false) } }
  const status = async (row, next) => { const pin = next === 'assigned' ? null : window.prompt(next === 'in_progress' ? 'Enter start PIN' : 'Enter completion PIN'); if (next !== 'assigned' && !pin) return; setBusy(true); try { await apiRequest(`/bookings/${row.id}/status`, 'PUT', { status: next, ...(pin ? { pin_code: pin } : {}) }, token); await load() } catch (error) { setMessage(error.message) } finally { setBusy(false) } }
  const upload = async (event, row, kind) => { const files = [...event.target.files]; if (!files.length) return; if (files.some((file) => !['image/jpeg', 'image/png'].includes(file.type) || file.size > 5 * 1024 * 1024)) return setMessage('Only JPEG/PNG images up to 5 MB are allowed.'); const form = new FormData(); form.append('kind', kind); files.forEach((file) => form.append('photos', file)); setBusy(true); try { await apiRequest(`/bookings/${row.id}/photos`, 'POST', form, token); setMessage(`${kind} photo uploaded securely.`); event.target.value = ''; await load() } catch (error) { setMessage(error.message) } finally { setBusy(false) } }
  return <main className="pd luxora-shell" style={{ color: '#eee' }}>
    <header className="portal-hero"><div><p className="luxora-eyebrow">Provider operations</p><h1 className="luxora-heading">Today’s service desk.</h1><p>See your schedule, keep availability current and complete each service with confidence.</p></div><button className="portal-signout" onClick={() => { sessionStorage.clear(); navigate('/login') }}>Sign out</button></header>
    {message && <p role="status" style={{ color: '#f4cf67' }}>{message}</p>}
    <section style={panel}><h2>Availability</h2><select value={availability} onChange={(event) => setAvailability(event.target.value)} style={{ padding: '.55rem', marginRight: '.5rem' }}><option value="available">Available</option><option value="busy">Busy</option><option value="offline">Offline</option></select><button style={button} disabled={busy} onClick={saveAvailability}>Save availability</button></section>
    <section style={panel}><h2>Earnings</h2><p><strong>LKR {Number(earnings.earnings || 0).toLocaleString()}</strong> total from {earnings.completedJobs || 0} completed services.</p><h3>Recent earnings history</h3>{earnings.history?.filter((row) => row.status === 'completed').map((row) => <p key={row.id}>#{row.id} {row.service_title} — {row.customer_name}; {row.booking_date}; LKR {Number(row.job_earnings || 0).toLocaleString()} ({row.payment_status})</p>)}</section>
    <section style={panel}><h2>My schedule</h2><label>Day <input type="date" value={scheduleDate} onChange={(event) => setScheduleDate(event.target.value)} /></label>{bookings.filter((row) => row.providerId && row.bookingDate === scheduleDate).sort((a, b) => String(a.bookingTime).localeCompare(String(b.bookingTime))).map((row) => <p key={row.id}><b>{row.bookingTime}</b>{row.expectedEndTime ? ` → ${new Date(row.expectedEndTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}` : ''} — {row.service_title}; {row.customer_name}; {row.town}; <b>{row.status}</b></p>)}{!bookings.some((row) => row.providerId && row.bookingDate === scheduleDate) && <p>No assigned bookings for this day.</p>}<h3>Upcoming bookings</h3>{bookings.filter((row) => row.providerId && row.status !== 'completed' && row.status !== 'cancelled').sort((a, b) => `${a.bookingDate} ${a.bookingTime}`.localeCompare(`${b.bookingDate} ${b.bookingTime}`)).slice(0, 8).map((row) => <p key={row.id}>{row.bookingDate} {row.bookingTime} — {row.service_title}; {row.customer_name}; {row.town}; <b>{row.status}</b></p>)}</section>
    <section style={panel}><p className="luxora-eyebrow">Execution queue</p><h2>Assigned and claimable bookings</h2>{bookings.length ? bookings.map((row) => <article className="booking-row" key={row.id}><div><span className="luxora-badge" data-status={row.status}>{row.status}</span><strong>#{row.id} {row.service_title}</strong><small>{row.customer_name} · {row.bookingDate} at {row.bookingTime} · {row.town || 'Town unavailable'}</small></div><div style={{ marginTop: '.5rem' }}>{row.status === 'pending' && <button style={button} disabled={busy} onClick={() => status(row, 'assigned')}>Accept booking</button>}{row.status === 'assigned' && <><label style={{ ...button, display: 'inline-block' }}>1. Upload BEFORE photo<input hidden type="file" accept="image/jpeg,image/png" multiple onChange={(event) => upload(event, row, 'BEFORE')} /></label><button style={button} disabled={busy} onClick={() => status(row, 'in_progress')}>2. Start with PIN</button></>}{row.status === 'in_progress' && <><label style={{ ...button, display: 'inline-block' }}>3. Upload AFTER photo<input hidden type="file" accept="image/jpeg,image/png" multiple onChange={(event) => upload(event, row, 'AFTER')} /></label><button style={button} disabled={busy} onClick={() => status(row, 'completed')}>4. Complete with PIN</button></>}</div></article>) : <p className="empty-copy">No assigned work yet. Keep your availability current to receive matching bookings.</p>}</section>
  </main>
}
