import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { apiRequest } from '../services/api'
import PortalShell, { EmptyState, Panel, Status } from '../components/PortalShell'
import ProviderCalendar from '../components/ProviderCalendar'
import { ConfirmDialog, FilterPills, PromptDialog } from '../components/ui'
import './ProviderDashboard.css'
import './ProviderOg.css'

const sessionUser = () => { try { return JSON.parse(sessionStorage.getItem('user') || 'null') } catch { return null } }

export default function ProviderDashboard() {
  const navigate = useNavigate(); const token = sessionStorage.getItem('token')
  const [availability, setAvailability] = useState('available'); const [bookings, setBookings] = useState([]); const [earnings, setEarnings] = useState({ earnings: 0, completedJobs: 0, history: [] }); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  const [scheduleDate, setScheduleDate] = useState(() => new Date().toISOString().slice(0, 10))
  const [dialog, setDialog] = useState(null)
  const [queueFilter, setQueueFilter] = useState('all')
  const load = async () => { if (!token) return navigate('/login', { replace: true }); try { const [availabilityRow, bookingRows, earningRow] = await Promise.all([apiRequest('/provider/availability', 'GET', null, token), apiRequest('/bookings/assigned', 'GET', null, token), apiRequest('/provider/earnings', 'GET', null, token)]); setAvailability(availabilityRow.availability_status); setBookings(bookingRows); setEarnings(earningRow) } catch (error) { setMessage(error.message) } }
  useEffect(() => { load() }, [])
  const saveAvailability = async () => { setBusy(true); try { await apiRequest('/provider/availability', 'PUT', { availability_status: availability }, token); setMessage('Availability saved.'); await load() } catch (error) { setMessage(error.message) } finally { setBusy(false) } }
  const submitStatus = async (pin) => { const { row, next } = dialog; setBusy(true); try { await apiRequest(`/bookings/${row.id}/status`, 'PUT', { status: next, ...(pin ? { pin_code: pin } : {}) }, token); setDialog(null); await load() } catch (error) { setMessage(error.message); setDialog(null) } finally { setBusy(false) } }
  const upload = async (event, row, kind) => { const files = [...event.target.files]; if (!files.length) return; if (files.some((file) => !['image/jpeg', 'image/png'].includes(file.type) || file.size > 5 * 1024 * 1024)) return setMessage('Only JPEG/PNG images up to 5 MB are allowed.'); const form = new FormData(); form.append('kind', kind); files.forEach((file) => form.append('photos', file)); setBusy(true); try { await apiRequest(`/bookings/${row.id}/photos`, 'POST', form, token); setMessage(`${kind} photo uploaded securely.`); event.target.value = ''; await load() } catch (error) { setMessage(error.message) } finally { setBusy(false) } }
  const saveSettings = async (values) => { setBusy(true); try { const user = sessionUser(); if (values.name && values.name !== (user?.name || '')) await apiRequest('/profile', 'PUT', { name: values.name }, token); if (values.service_towns !== undefined && values.service_towns !== '') await apiRequest('/provider/service-towns', 'PUT', { service_towns: values.service_towns }, token); setMessage('Provider settings saved.'); setDialog(null); await load() } catch (error) { setMessage(error.message); setDialog(null) } finally { setBusy(false) } }
  const todayRows = bookings.filter((row) => row.providerId && row.bookingDate === scheduleDate).sort((a, b) => String(a.bookingTime).localeCompare(String(b.bookingTime)))
  const upcomingRows = bookings.filter((row) => row.providerId && !['completed', 'cancelled'].includes(String(row.status).toLowerCase())).sort((a, b) => `${a.bookingDate} ${a.bookingTime}`.localeCompare(`${b.bookingDate} ${b.bookingTime}`)).slice(0, 8)
  const nextService = upcomingRows[0]
  const queueCounts = bookings.reduce((counts, row) => { const key = String(row.status).toLowerCase(); counts[key] = (counts[key] || 0) + 1; return counts }, {})
  const queueRows = queueFilter === 'all' ? bookings : bookings.filter((row) => (queueFilter === 'claimable' ? String(row.status).toLowerCase() === 'pending' && !row.providerId : String(row.status).toLowerCase() === queueFilter))
  const claimableCount = bookings.filter((row) => String(row.status).toLowerCase() === 'pending' && !row.providerId).length
  const queuePillOptions = [{ value: 'all', label: 'All', count: bookings.length }, ...(claimableCount ? [{ value: 'claimable', label: 'Claimable', count: claimableCount }] : []), ...['assigned', 'in_progress', 'completed'].filter((status) => queueCounts[status]).map((status) => ({ value: status, label: status.replace('_', ' '), count: queueCounts[status] }))]
  const providerUser = sessionUser()
  return <PortalShell role="Provider" userName={providerUser?.name || 'Service partner'} title="Dashboard overview" heroTitle={`Welcome back, ${(providerUser?.name || 'Provider').split(' ')[0]}.`} subtitle={`You have ${todayRows.length} ${todayRows.length === 1 ? 'service' : 'services'} scheduled. Keep every detail moving with confidence.`} notice={message} onSignOut={() => { sessionStorage.clear(); navigate('/login') }} navItems={[{ id: 'overview', label: 'Overview' }, { id: 'schedule', label: "Today's schedule" }, { id: 'queue', label: 'Execution queue' }, { id: 'availability', label: 'Availability' }, { id: 'earnings', label: 'Earnings' }]}>
    <section className="provider-quick-metrics" aria-label="Provider summary"><article><span>Active bookings</span><strong>{upcomingRows.length}</strong></article><article><span>Total earnings</span><strong>LKR {Number(earnings.earnings || 0).toLocaleString()}</strong></article><article><span>Next service</span><strong>{nextService ? new Date(nextService.bookingDate).toLocaleDateString(undefined, { year: 'numeric', month: '2-digit', day: '2-digit' }) : 'Clear'}</strong></article></section>
    <div className="provider-overview"><Panel id="availability" className="provider-availability"><p className="portal-kicker">Availability</p><div className="provider-availability-row"><div><Status tone={availability}>{availability}</Status><h2>Ready when you are.</h2><p>Update your working state so Luxora can match the right service to your day.</p></div><div className="availability-controls"><select value={availability} onChange={(event) => setAvailability(event.target.value)}><option value="available">Available</option><option value="busy">Busy</option><option value="offline">Offline</option></select><button className="ui-button ui-button--primary" disabled={busy} onClick={saveAvailability}>Save availability</button><button className="ui-button ui-button--secondary" disabled={busy} onClick={() => setDialog({ type: 'settings' })}>Provider settings</button></div></div></Panel><Panel id="earnings" className="provider-earnings"><p className="portal-kicker">Earnings</p><strong>LKR {Number(earnings.earnings || 0).toLocaleString()}</strong><p>from {earnings.completedJobs || 0} completed services</p><div className="earnings-history">{earnings.history?.filter((row) => row.status === 'completed').slice(0, 3).map((row) => <div key={row.id}><span>{row.service_title}</span><b>LKR {Number(row.job_earnings || 0).toLocaleString()}</b></div>)}</div></Panel></div>
    <Panel id="schedule" className="provider-schedule"><div className="section-heading"><div><p className="portal-kicker">Schedule</p><h2>Your service rhythm</h2></div><label className="date-picker"><span>Schedule day</span><input type="date" value={scheduleDate} onChange={(event) => setScheduleDate(event.target.value)} /></label></div><div className="provider-schedule-grid"><ProviderCalendar bookings={bookings} selected={scheduleDate} onSelect={setScheduleDate} />{todayRows.length ? <div className="schedule-timeline">{todayRows.map((row) => <article key={row.id}><time>{row.bookingTime}</time><div className="timeline-dot" /><div><Status tone={String(row.status).toLowerCase()}>{row.status}</Status><h3>{row.service_title}</h3><p>{row.customer_name} · {row.town || 'Location details available in service'}</p></div><small>{row.expectedEndTime ? `Ends ${new Date(row.expectedEndTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}` : `Booking #${row.id}`}</small></article>)}</div> : <EmptyState title="Your schedule is clear">Enjoy the downtime, or keep your availability open to receive matching work.</EmptyState>}</div></Panel>
    <Panel id="queue" className="provider-queue"><p className="portal-kicker">Execution queue</p><h2>Assigned and claimable bookings</h2><div style={{ margin: '12px 0' }}><FilterPills ariaLabel="Filter queue" value={queueFilter} onChange={setQueueFilter} options={queuePillOptions} /></div>{queueRows.length ? <div className="execution-grid">{queueRows.map((row) => <article className="execution-card" key={row.id}><div className="execution-card-head"><Status tone={String(row.status).toLowerCase()}>{row.status}</Status><small>#{row.id}</small></div><h3>{row.service_title}</h3><p>{row.customer_name}</p><dl><div><dt>When</dt><dd>{row.bookingDate} · {row.bookingTime}</dd></div><div><dt>Where</dt><dd>{row.town || 'Town unavailable'}</dd></div></dl><ol><li className={['assigned', 'in_progress', 'completed'].includes(String(row.status).toLowerCase()) ? 'done' : ''}>Confirm service</li><li className={['in_progress', 'completed'].includes(String(row.status).toLowerCase()) ? 'done' : ''}>Before photos & start PIN</li><li className={String(row.status).toLowerCase() === 'completed' ? 'done' : ''}>Complete with proof</li></ol><div className="execution-actions">{String(row.status).toLowerCase() === 'pending' && <button className="ui-button ui-button--primary" disabled={busy} onClick={() => setDialog({ type: 'accept', row })}>Accept service</button>}{String(row.status).toLowerCase() === 'assigned' && <><label className="ui-button ui-button--secondary">Upload before<input hidden type="file" accept="image/jpeg,image/png" multiple onChange={(event) => upload(event, row, 'BEFORE')} /></label><button className="ui-button ui-button--primary" disabled={busy} onClick={() => setDialog({ type: 'pin', row, next: 'in_progress' })}>Start with PIN</button></>}{String(row.status).toLowerCase() === 'in_progress' && <><label className="ui-button ui-button--secondary">Upload after<input hidden type="file" accept="image/jpeg,image/png" multiple onChange={(event) => upload(event, row, 'AFTER')} /></label><button className="ui-button ui-button--primary" disabled={busy} onClick={() => setDialog({ type: 'pin', row, next: 'completed' })}>Complete with PIN</button></>}</div></article>)}</div> : <EmptyState title="No services in this view">Keep your availability current to receive matching Luxora work.</EmptyState>}</Panel>
    <Panel className="provider-upcoming"><p className="portal-kicker">Upcoming</p><h2>What comes next</h2>{upcomingRows.length ? <div className="upcoming-list">{upcomingRows.map((row) => <article key={row.id}><time>{new Date(row.bookingDate).toLocaleDateString(undefined, { day: 'numeric', month: 'short' })}</time><b>{row.bookingTime}</b><span>{row.service_title} · {row.customer_name}</span><Status tone={String(row.status).toLowerCase()}>{row.status}</Status></article>)}</div> : <EmptyState title="Nothing upcoming">New work will appear here as it is assigned.</EmptyState>}</Panel>

    {dialog?.type === 'accept' && <ConfirmDialog title="Accept this service?" message={`${dialog.row.service_title} · ${dialog.row.bookingDate} at ${dialog.row.bookingTime} in ${dialog.row.town || 'your area'}. Accepting assigns this booking to you.`} confirmLabel="Accept service" onConfirm={() => submitStatus(null)} onClose={() => setDialog(null)} />}
    {dialog?.type === 'pin' && <PromptDialog kicker={`Booking #${dialog.row.id}`} title={dialog.next === 'in_progress' ? 'Enter start PIN' : 'Enter completion PIN'} submitLabel={dialog.next === 'in_progress' ? 'Start service' : 'Complete service'} fields={[{ name: 'pin', label: '6-digit PIN', type: 'text', inputMode: 'numeric', required: true, maxLength: 6, initial: '', placeholder: '••••••', full: true, hint: 'The customer shares this PIN at the door.' }]} onSubmit={(values) => submitStatus(values.pin)} onClose={() => setDialog(null)} />}
    {dialog?.type === 'settings' && <PromptDialog kicker="Provider settings" title="Your working profile" submitLabel="Save settings" fields={[{ name: 'name', label: 'Display name', type: 'text', required: true, initial: providerUser?.name || '', maxLength: 100, full: true }, { name: 'service_towns', label: 'Towns served (comma-separated)', type: 'textarea', initial: '', placeholder: 'Colombo, Colombo 03, Kandy', maxLength: 400, full: true, hint: 'Up to 10 towns. Leave empty to keep your current towns.' }]} onSubmit={saveSettings} onClose={() => setDialog(null)} />}
  </PortalShell>
}
